force-app/main/default/objects/GsGoal__c/GsGoal__c.object-meta.xml
<CustomObject>
    <description>Main object of the GoalSetter application. It is used to capture all goal related data.</description>
    <label>Goal</label>
    <nameField>
        <label>Study</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GsGoal__c/fields/GsAchievedDate__c.field-meta.xml
<CustomField>
    <fullName>GsAchievedDate__c</fullName>
    <description>The exact date the goal was achieved</description>
    <label>Achieved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsComments__c.field-meta.xml
<CustomField>
    <fullName>GsComments__c</fullName>
    <description>This field can be entered whenever the goal is created or edited with the “New Goal” or “Edit Goal” flows.</description>
    <label>Comments</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsCroGoal__c.field-meta.xml
<CustomField>
    <fullName>GsCroGoal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if a goal is a CRO goal (used for historical goals and Sophia API)</description>
    <label>CRO Goal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsFinal__c.field-meta.xml
<CustomField>
    <fullName>GsFinal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the goal is final/frozen</description>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsGoalPeriod__c.field-meta.xml
<CustomField>
    <fullName>GsGoalPeriod__c</fullName>
    <description>Goal Period is the Master-Detail reference to the Goal Setter period</description>
    <inlineHelpText>Within this period that goal has to be achieved.</inlineHelpText>
    <label>Goal Period</label>
    <referenceTo>GsGoalPeriod__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsGoalTitle__c.field-meta.xml
<CustomField>
    <fullName>GsGoalTitle__c</fullName>
    <description>The goal title is either written automatically by the “New Goal”, “Edit Goal” or “Revise Goal” flow in case a certain standard goal was selected. In this case, the value from the selected standard goal is copied. If the standard goal contains a placeholder, the replacement value will also be inserted. If the standard goal is set to “-- enter goal manually --&quot;, the goal title is entered manually.</description>
    <label>Goal Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsLabcorpIncentiveGoal__c.field-meta.xml
<CustomField>
    <fullName>GsLabcorpIncentiveGoal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a goal is an incentive goal</description>
    <label>Labcorp Incentive Goal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsProgram__c.field-meta.xml
<CustomField>
    <fullName>GsProgram__c</fullName>
    <description>The program (BAY-Number) is written automatically by the “New Goal” flow based on the selected study by the user. The data is retrieved from IMPACT.</description>
    <label>Program</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsProject__c.field-meta.xml
<CustomField>
    <fullName>GsProject__c</fullName>
    <description>The project is being written automatically by the “New Goal” flow unless the user creates a clinical team goal record type and selects “General” for study. In this case, the project needs to be selected manually by the user. All study and project information is retrieved from IMPACT.</description>
    <label>Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsRevised__c.field-meta.xml
<CustomField>
    <fullName>GsRevised__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the goal is revised</description>
    <label>Revised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsStatus__c.field-meta.xml
<CustomField>
    <fullName>GsStatus__c</fullName>
    <description>Picklist for the goal&apos;s status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Achieved</fullName>
            </value>
            <value>
                <fullName>Not Achieved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsStudyNumber__c.field-meta.xml
<CustomField>
    <fullName>GsStudyNumber__c</fullName>
    <description>The goal&apos;s study number</description>
    <label>Study Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsTargetFormula__c.field-meta.xml
<CustomField>
    <fullName>GsTargetFormula__c</fullName>
    <description>This formula field prints the “Target Date” in a user-friendly format depending on the goal record type. Cosmos goals (LabCorp, Parexel) require a date including a day.</description>
    <formula>IF(OR(ISNULL( GsTargetDate__c ), ISBLANK(GsTargetDate__c )),
&quot;&quot;,
CASE(MONTH(GsTargetDate__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;&quot;) &amp;

IF( OR( RecordType.DeveloperName = &quot;LabCorp_Goal&quot;, RecordType.DeveloperName = &quot;GsParexelGoal&quot;), &quot; &quot; &amp; TEXT(DAY(GsTargetDate__c )) &amp; &quot;, &quot; , &quot; &quot;)
&amp; TEXT(YEAR(GsTargetDate__c ))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsWithdrawn__c.field-meta.xml
<CustomField>
    <fullName>GsWithdrawn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the goal is withdrawn</description>
    <label>Withdrawn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsWithdrawnComment__c.field-meta.xml
<CustomField>
    <fullName>GsWithdrawnComment__c</fullName>
    <description>The user is prompted to enter a comment for withdrawn goals during the “Withdraw Goal” flow. It will be cleared automatically in the “Undo Withdrawal” flow.</description>
    <label>Withdrawn Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GsGoalPeriod__c/GsGoalPeriod__c.object-meta.xml
<CustomObject>
    <description>A goal period defines the period for which goals are created, maintained and tracked. Each period is divided into an edit phase and the goal tracking phase.</description>
    <label>Goal Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoalController.cls
public with sharing class GoalController {
  @AuraEnabled(cacheable=true)
  public static List<GsGoal__c> getGoals(
    String year,
    String searchInput,
    List<String> recordTypes,
    List<String> status,
    List<String> flags
  ) {
    try {
      // we initialize a list of goals to be returned
      List<GsGoal__c> goals = new List<GsGoal__c>();
      // we have to compile a dynamic SOQL string
      String whereSearch = '';
      // we always check if the value is not present as it will not be filtered
      // if it is present we add it to searchstring with the appropriate search params
      // if the string is empty a WHERE has to be added otherwise only ANDs
      if (year != null && !year.equals('')) {
        whereSearch +=
          (whereSearch.equals('') ? ' WHERE ' : ' AND ') +
          'GsGoalPeriod__c = :year';
      }
      if (recordTypes != null && recordTypes.size() != 0) {
        whereSearch +=
          (whereSearch.equals('') ? ' WHERE ' : ' AND ') +
          'RecordTypeId IN :recordTypes';
      }
      if (status != null && status.size() != 0) {
        whereSearch +=
          (whereSearch.equals('') ? ' WHERE ' : ' AND ') +
          'GsStatus__c IN :status';
      }
      if (flags != null) {
        for (String flag : flags) {
          whereSearch +=
            (whereSearch.equals('') ? ' WHERE ' : ' AND ') +
            flag +
            ' = TRUE';
        }
      }
      // The fields we want to slect
      String fields = 'GsProgram__c, GsProject__c, GsStudyNumber__c, GsGoalTitle__c, GsTargetFormula__c, GsStatus__c, GsFinal__c, GsCroGoal__c, GsRevised__c, GsComments__c, GsLabcorpIncentiveGoal__c, GsWithdrawn__c, GsWithdrawnComment__c, GsAchievedDate__c, RecordType.Name, Id, GsGoalPeriod__c';
      // The list will be filled either using SOSL or SOQL dependent on if there is a search phrase present
      if (searchInput != null && !searchInput.equals('')) {
        String query =
          'FIND :searchInput' +
          ' RETURNING GsGoal__c(' +
          fields +
          whereSearch +
          ' ORDER BY GsProgram__c, GsProject__c, GsStudyNumber__c)';
        goals = Search.query(query)[0];
      } else {
        String query =
          'SELECT ' +
          fields +
          ' FROM GsGoal__c' +
          whereSearch +
          ' ORDER BY GsProgram__c, GsProject__c, GsStudyNumber__c';
        goals = Database.query(query);
      }
      Integer sameProgram = 0;
      Integer sameProject = 0;
      Integer sameStudy = 0;
      // we iterate over all goals
      // if the previous entry has the same Program, Project and/or Study we null the field
      // so it appears in the frontend as a wonderful table wherer doubled entries are not shown
      for (Integer i = 1; i < goals.size(); i++) {
        GsGoal__c goal = goals[i];
        if (
          goal.GsProgram__c != null &&
          goal.GsProgram__c.equals(goals[sameProgram].GsProgram__c)
        ) {
          goal.GsProgram__c = '';
          if (
            goal.GsProject__c != null &&
            goal.GsProject__c.equals(goals[sameProject].GsProject__c)
          ) {
            goal.GsProject__c = '';
            if (
              goal.GsStudyNumber__c != null &&
              goal.GsStudyNumber__c.equals(goals[sameStudy].GsStudyNumber__c)
            ) {
              goal.GsStudyNumber__c = '';
            } else {
              sameStudy = i;
            }
          } else {
            sameProject = i;
            sameStudy = i;
          }
        } else {
          sameProgram = i;
          sameProject = i;
          sameStudy = i;
        }
      }
      return goals;
    } catch (Exception e) {
      HandleCustomException.logException(e);
      throw e;
    }
  }

  @AuraEnabled(cacheable=true)
  // we simply return all goal periods from the database using SOQL
  public static List<GsGoalPeriod__c> getGoalPeriods() {
    try {
      return [
        SELECT Name, Id
        FROM GsGoalPeriod__c
        ORDER BY Name
      ];
    } catch (Exception e) {
      HandleCustomException.logException(e);
      throw e;
    }
  }
}