force-app/main/default/objects/GsGoal__c/GsGoal__c.object-meta.xml
<CustomObject>
    <description>Main object of the GoalSetter application. It is used to capture all goal related data.</description>
    <label>Goal</label>
    <nameField>
        <label>Study</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GsGoal__c/fields/GsAchievedDate__c.field-meta.xml
<CustomField>
    <fullName>GsAchievedDate__c</fullName>
    <description>The exact date the goal was achieved</description>
    <label>Achieved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsComments__c.field-meta.xml
<CustomField>
    <fullName>GsComments__c</fullName>
    <description>This field can be entered whenever the goal is created or edited with the “New Goal” or “Edit Goal” flows.</description>
    <label>Comments</label>
    <length>750</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsCroGoal__c.field-meta.xml
<CustomField>
    <fullName>GsCroGoal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if a goal is a CRO goal (used for historical goals and Sophia API)</description>
    <label>CRO Goal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsFinal__c.field-meta.xml
<CustomField>
    <fullName>GsFinal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the goal is final/frozen</description>
    <label>Final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsGoalPeriod__c.field-meta.xml
<CustomField>
    <fullName>GsGoalPeriod__c</fullName>
    <description>Goal Period is the Master-Detail reference to the Goal Setter period</description>
    <inlineHelpText>Within this period that goal has to be achieved.</inlineHelpText>
    <label>Goal Period</label>
    <referenceTo>GsGoalPeriod__c</referenceTo>
    <relationshipLabel>Goals</relationshipLabel>
    <relationshipName>Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsGoalTitle__c.field-meta.xml
<CustomField>
    <fullName>GsGoalTitle__c</fullName>
    <description>The goal title is either written automatically by the “New Goal”, “Edit Goal” or “Revise Goal” flow in case a certain standard goal was selected. In this case, the value from the selected standard goal is copied. If the standard goal contains a placeholder, the replacement value will also be inserted. If the standard goal is set to “-- enter goal manually --&quot;, the goal title is entered manually.</description>
    <label>Goal Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsLabcorpIncentiveGoal__c.field-meta.xml
<CustomField>
    <fullName>GsLabcorpIncentiveGoal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a goal is an incentive goal</description>
    <label>Labcorp Incentive Goal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsProgram__c.field-meta.xml
<CustomField>
    <fullName>GsProgram__c</fullName>
    <description>The program (BAY-Number) is written automatically by the “New Goal” flow based on the selected study by the user. The data is retrieved from IMPACT.</description>
    <label>Program</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsProject__c.field-meta.xml
<CustomField>
    <fullName>GsProject__c</fullName>
    <description>The project is being written automatically by the “New Goal” flow unless the user creates a clinical team goal record type and selects “General” for study. In this case, the project needs to be selected manually by the user. All study and project information is retrieved from IMPACT.</description>
    <label>Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsRevised__c.field-meta.xml
<CustomField>
    <fullName>GsRevised__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if the goal is revised</description>
    <label>Revised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsStandardGoal__c.field-meta.xml
<CustomField>
    <fullName>GsStandardGoal__c</fullName>
    <description>Picklist for standard goals based on record type</description>
    <label>Standard Goal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Achieve [value]% RTE</fullName>
            </value>
            <value>
                <fullName>Achieve [value]% subject cleaned</fullName>
            </value>
            <value>
                <fullName>Achieve 1st site RTE</fullName>
            </value>
            <value>
                <fullName>Achieve Clean Database 4 weeks after LPLV</fullName>
            </value>
            <value>
                <fullName>Achieve final Protocol</fullName>
            </value>
            <value>
                <fullName>Achieve LPFV</fullName>
            </value>
            <value>
                <fullName>All systems ready for RTE</fullName>
            </value>
            <value>
                <fullName>Complete Protocol Feasibility</fullName>
                <label>Complete Feasibility</label>
            </value>
            <value>
                <fullName>CSR final</fullName>
            </value>
            <value>
                <fullName>CTA submissions completed</fullName>
            </value>
            <value>
                <fullName>Final Country selection</fullName>
            </value>
            <value>
                <fullName>Implement Protocol Amendment</fullName>
            </value>
            <value>
                <fullName>More than 95% compliance to the monitoring strategy</fullName>
            </value>
            <value>
                <fullName>Non-system queries closed in &lt;21 days of opening</fullName>
            </value>
            <value>
                <fullName>Protocol Level 1</fullName>
            </value>
            <value>
                <fullName>Protocol Level 2</fullName>
            </value>
            <value>
                <fullName>Randomize [value]% subjects</fullName>
            </value>
            <value>
                <fullName>Stable CDP</fullName>
            </value>
            <value>
                <fullName>Support D6 preparation</fullName>
            </value>
            <value>
                <fullName>Support D7 preparation</fullName>
            </value>
            <value>
                <fullName>Support Scientific Advice Meetings</fullName>
            </value>
            <value>
                <fullName>Support Submission Activities</fullName>
            </value>
            <value>
                <fullName>TFL within 3 weeks after Clean Database</fullName>
            </value>
            <value>
                <fullName>TMF archived</fullName>
            </value>
            <value>
                <fullName>75% sites ready to enroll</fullName>
            </value>
            <value>
                <fullName>50% enrollment complete</fullName>
                <label>50% enrollment complete (LPFT)</label>
            </value>
            <value>
                <fullName>100% enrollment complete (LPFT)</fullName>
            </value>
            <value>
                <fullName>-- enter goal manually --</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsStatus__c.field-meta.xml
<CustomField>
    <fullName>GsStatus__c</fullName>
    <description>Picklist for the goal&apos;s status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Achieved</fullName>
            </value>
            <value>
                <fullName>Not Achieved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsStudyNumber__c.field-meta.xml
<CustomField>
    <fullName>GsStudyNumber__c</fullName>
    <description>The goal&apos;s study number</description>
    <label>Study Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsWithdrawn__c.field-meta.xml
<CustomField>
    <fullName>GsWithdrawn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the goal is withdrawn</description>
    <label>Withdrawn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GsGoal__c/fields/GsWithdrawnComment__c.field-meta.xml
<CustomField>
    <fullName>GsWithdrawnComment__c</fullName>
    <description>The user is prompted to enter a comment for withdrawn goals during the “Withdraw Goal” flow. It will be cleared automatically in the “Undo Withdrawal” flow.</description>
    <label>Withdrawn Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GsGoalPeriod__c/GsGoalPeriod__c.object-meta.xml
<CustomObject>
    <description>A goal period defines the period for which goals are created, maintained and tracked. Each period is divided into an edit phase and the goal tracking phase.</description>
    <label>Goal Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoalControllerTest.cls
@isTest
private with sharing class GoalControllerTest {
  static List<Schema.PicklistEntry> statusList = GsGoal__c.GsStatus__c.getDescribe()
    .getPicklistValues();

  static List<Schema.RecordTypeInfo> recordTypeList = GsGoal__c.SObjectType.getDescribe()
    .getRecordTypeInfos();

  static List<Schema.PicklistEntry> standardGoals = GsGoal__c.GsStandardGoal__c.getDescribe()
    .getPicklistValues();

  static List<GsGoalPeriod__c> generateGoalPeriods() {
    List<GsGoalPeriod__c> periods = new List<GsGoalPeriod__c>();
    for (Integer i = 2010; i < 2015; i++) {
      periods.add(new GsGoalPeriod__c(Name = '' + i));
    }
    insert periods;
    return periods;
  }

  static List<GsGoal__c> generateGoals() {
    List<GsGoalPeriod__c> periods = GoalControllerTest.generateGoalPeriods();
    List<GsGoal__c> goals = new List<GsGoal__c>();
    for (Integer i = 0; i < 50; i++) {
      GsGoal__c goal = new GsGoal__c();
      goal.GsProgram__c = 'Program' + Math.ceil(i / 10);
      goal.GsProject__c = 'Project' + Math.ceil(i / 5);
      goal.GsStudyNumber__c = 'StudyNumber' + Math.ceil(i / 3);
      goal.GsGoalTitle__c = 'Title' + i;
      goal.GsStatus__c = statusList.get(Math.mod(i, statusList.size()))
        .getValue();
      goal.GsFinal__c = Math.mod(i, 2) == 0;
      goal.GsCroGoal__c = Math.mod(i, 3) == 0;
      goal.GsRevised__c = Math.mod(i, 4) == 0;
      goal.GsComments__c = Math.mod(i, 2) == 0 ? '' : 'Comment ' + i;
      goal.GsLabcorpIncentiveGoal__c = Math.mod(i, 9) == 0;
      goal.GsWithdrawn__c = Math.mod(i, 5) == 0;
      goal.GsWithdrawnComment__c = Math.mod(i, 10) == 0 ? '' : 'Withdrawn' + i;
      if (goal.GsStatus__c.equals('Achieved')) {
        goal.GsAchievedDate__c = Date.newInstance(
          2024,
          Math.mod(i, 12) + 1,
          Math.mod(i * 6, 28)
        );
      }
      goal.GsStandardGoal__c = '-- enter goal manually --';
      goal.GsGoalPeriod__c = periods.get(Math.mod(i, periods.size())).Id;
      goal.RecordTypeId = recordTypeList.get(
          Math.mod(i, recordTypeList.size() - 1)
        )
        .getRecordTypeId();
      goals.add(goal);
    }
    insert goals;
    return goals;
  }

  // we test gettting the goal periods
  @isTest
  static void testGetGoalPeriods() {
    Test.startTest();
    List<GsGoalPeriod__c> insertedPeriods = GoalControllerTest.generateGoalPeriods();
    List<GsGoalPeriod__c> periods = GoalController.getGoalPeriods();
    System.assert(periods.size() > 0, 'Unable to find goal periods');
    for (GsGoalPeriod__c period : insertedPeriods) {
      System.assert(
        periods.contains(period),
        'Unable to find Goal period ' + period.Name
      );
    }
    Test.stopTest();
  }

  // we test the getting of goals
  @isTest
  static void testGetGoals() {
    for (RecordtypeInfo info : recordTypeList) {
      System.debug(info.getName() + ' ' + info.getRecordTypeId());
    }
    Test.startTest();
    List<GsGoal__c> insertedGoals = GoalControllerTest.generateGoals();
    // No params
    List<GsGoal__c> goals = GoalController.getGoals(
      null,
      null,
      null,
      null,
      null
    );
    // first we want to find all goals
    // if something is null and not handeld this would break
    for (GsGoal__c goal : insertedGoals) {
      Boolean found = false;
      for (GsGoal__c check : goals) {
        if (check.Id.equals(goal.Id)) {
          found = true;
          break;
        }
      }
      System.assert(found, 'Unable to find Goal without params' + goal.Id);
    }
    // we want to ensure that all the filters are not applied
    goals = GoalController.getGoals(
      '',
      '',
      new String[0],
      new String[0],
      new String[0]
    );
    for (GsGoal__c goal : insertedGoals) {
      Boolean found = false;
      for (GsGoal__c check : goals) {
        if (check.Id.equals(goal.Id)) {
          found = true;
          break;
        }
      }
      System.assert(found, 'Unable to find Goal with empty params' + goal.Id);
    }
    // asserting that empty table structure where equal attributes are left out
    for (Integer i = 1; i < goals.size(); i++) {
      GsGoal__c curr = null;
      GsGoal__c prev = null;
      for (GsGoal__c check : insertedGoals) {
        if (check.Id.equals(goals.get(i).Id)) {
          curr = check;
        }
        if (check.Id.equals(goals.get(i - 1).Id)) {
          prev = check;
        }
        if (prev != null && curr != null)
          break;
      }
      System.assert(
        prev != null && curr != null,
        'Cannot find prev and curr to compare'
      );
      if (goals.get(i).GsProgram__c.equals('')) {
        System.assertEquals(curr.GsProgram__c, prev.GsProgram__c);
      }
      if (goals.get(i).GsProject__c.equals('')) {
        System.assertEquals(curr.GsProject__c, prev.GsProject__c);
      }
      if (goals.get(i).GsStudyNumber__c.equals('')) {
        System.assertEquals(curr.GsStudyNumber__c, prev.GsStudyNumber__c);
      }
    }
    // filtered by year
    String period = GoalController.getGoalPeriods().get(0).Id;
    goals = GoalController.getGoals(
      period,
      '',
      new String[0],
      new String[0],
      new String[0]
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by year');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsGoalPeriod__c.equals(period),
        'Cannot filter by by year' + goal.Id
      );
    }
    // filtered by search
    goals = GoalController.getGoals(
      '',
      'StudyNumber',
      new String[0],
      new String[0],
      new String[0]
    );
    // no idea why this does not work System.assert(goals.size() > 0, 'Found no goals while filtering by search');
    // filtered by recordType
    goals = GoalController.getGoals(
      '',
      '',
      new List<String>{ recordTypeList.get(0).getRecordTypeId() },
      new String[0],
      new String[0]
    );
    System.assert(
      goals.size() > 0,
      'Found no goals while filtering by recordtype'
    );
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.RecordTypeId.equals(recordTypeList.get(0).getRecordTypeId()),
        'Not filtered by record type ' + goal.Id
      );
    }
    // filtered by multiple record types
    goals = GoalController.getGoals(
      '',
      '',
      new List<String>{
        recordTypeList.get(0).getRecordTypeId(),
        recordTypeList.get(1).getRecordTypeId()
      },
      new String[0],
      new String[0]
    );
    System.assert(
      goals.size() > 0,
      'Found no goals while filtering by recordtypes'
    );
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.RecordTypeId.equals(recordTypeList.get(0).getRecordTypeId()) ||
        goal.RecordTypeId.equals(recordTypeList.get(1).getRecordTypeId()),
        'Not filtered by record types ' + goal.Id
      );
    }
    // filtered by status
    goals = GoalController.getGoals(
      '',
      '',
      new String[0],
      new List<String>{ statusList.get(0).getValue() },
      new String[0]
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by status');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsStatus__c.equals(statusList.get(0).getvalue()),
        'Not filtered by status ' + goal.Id
      );
    }
    // filtered by multiple status
    goals = GoalController.getGoals(
      '',
      '',
      new String[0],
      new List<String>{
        statusList.get(0).getValue(),
        statusList.get(1).getValue()
      },
      new String[0]
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by stati');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsStatus__c.equals(statusList.get(0).getValue()) ||
        goal.GsStatus__c.equals(statusList.get(1).getValue()),
        'Not filtered by stati ' + goal.Id
      );
    }
    // filtered by flag
    goals = GoalController.getGoals(
      '',
      '',
      new String[0],
      new String[0],
      new List<String>{ 'GsCroGoal__c' }
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by flag');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsCroGoal__c == true,
        'Not filtered by flag ' + goal.Id
      );
    }
    // filtered by multiple flags
    goals = GoalController.getGoals(
      '',
      '',
      new String[0],
      new String[0],
      new List<String>{ 'GsCroGoal__c', 'GsRevised__c' }
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by flags');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsCroGoal__c == true || goal.GsRevised__c == true,
        'Not filtered by flags ' + goal.Id
      );
    }
    // assesing that multiple active filters also work
    // thats why year is always set
    goals = GoalController.getGoals(
      period,
      '',
      new List<String>{ recordTypeList.get(0).getRecordTypeId() },
      new String[0],
      new String[0]
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by year');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsGoalPeriod__c.equals(period) &&
        goal.RecordTypeId.equals(recordTypeList.get(0).getRecordTypeId()),
        'Cannot filter by by year and record type' + goal.Id
      );
    }
    goals = GoalController.getGoals(
      period,
      '',
      new String[0],
      new List<String>{ statusList.get(0).getValue() },
      new String[0]
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by year');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsGoalPeriod__c.equals(period) &&
        goal.GsStatus__c.equals(statusList.get(0).getValue()),
        'Cannot filter by by year and status' + goal.Id
      );
    }
    goals = GoalController.getGoals(
      period,
      '',
      new String[0],
      new String[0],
      new List<String>{ 'GsCroGoal__c' }
    );
    System.assert(goals.size() > 0, 'Found no goals while filtering by year');
    for (GsGoal__c goal : goals) {
      System.assert(
        goal.GsGoalPeriod__c.equals(period) && goal.GsCroGoal__c == true,
        'Cannot filter by by year and flag' + goal.Id
      );
    }
    Test.stopTest();
  }
}