force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/CWID__c.field-meta.xml
<CustomField>
    <fullName>CWID__c</fullName>
    <label>CWID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Initial_Sending_Failed__c.field-meta.xml
<CustomField>
    <fullName>Initial_Sending_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when initial sending to Prima (triggered after changes are approved) results with error.</description>
    <label>Initial Sending Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PrimaData.cls
global class PrimaData {
     //Prima data class
     //comments added to test githuh-enhancement-destructive-v2
     //comments added to new branch
    public static final Set<String> NEW_STATUSES = new Set<String>{
        UserEntryData.STATUS_ASSIGN, 
        UserEntryData.STATUS_REMOVE
    };
    public static final Set<String> IN_PROGRESS_STATUSES = new Set<String>{
        UserEntryData.STATUS_ASSIGN_REQUESTED, 
        UserEntryData.STATUS_REMOVE_REQUESTED
    };

    public static Set<String> getUserCwids(List<UserResponse> users){
        Set<String> cwids = new Set<String>();
        for(UserResponse user : users){
            if(String.isNotBlank(user.cwid)){
                cwids.add(user.cwid);
            }
        }

        return cwids;
    }

    public static User_Prima_Role__c getUserPrimaRoleToUpdate(Id userPrimaRoleId, PrimaRoleResponse primaRole){
        User_Prima_Role__c userPrimaRole = new User_Prima_Role__c(
            Id = userPrimaRoleId, 
            Status__c = primaRole.status
        );
        userPrimaRole.Error_Message__c = primaRole.status == UserEntryData.STATUS_ERROR ? primaRole.error : null;
        userPrimaRole.Initial_Sending_Failed__c = false;
        return userPrimaRole;
    }

    public static User_Prima_Security_Group__c getUserPrimaSecurityGroupToUpdate(Id userPrimaSecurityGroupId, PrimaSecurityGroupResponse primaSecurityGroup){
        User_Prima_Security_Group__c userPrimaSecurityGroup = new User_Prima_Security_Group__c(
            Id = userPrimaSecurityGroupId, 
            Status__c = primaSecurityGroup.status
        );
        userPrimaSecurityGroup.Error_Message__c = primaSecurityGroup.status == UserEntryData.STATUS_ERROR ? primaSecurityGroup.error : null;
        userPrimaSecurityGroup.Initial_Sending_Failed__c = false;
        return userPrimaSecurityGroup;
    }

    global class UserRequest {
        public String cwid;
        public List<PrimaRoleRequest> primaRoles;
        public List<PrimaSecurityGroupRequest> primaSecurityGroups;

        public UserRequest(User_Entry__c userEntry){
            cwid = userEntry.CWID__c;
            primaRoles = new List<PrimaRoleRequest>();
            for(User_Prima_Role__c userRole : userEntry.User_Prima_Roles__r){
                primaRoles.add(new PrimaRoleRequest(userRole.Prima_Role__r.Name, userRole.Status__c));
            }
            primaSecurityGroups = new List<PrimaSecurityGroupRequest>();
            for(User_Prima_Security_Group__c userSecurityGroup : userEntry.User_Prima_Security_Groups__r){
                primaSecurityGroups.add(new PrimaSecurityGroupRequest(userSecurityGroup.Prima_Security_Group__r.Name, userSecurityGroup.Status__c));
            }
        }
    }

    global class UserResponse {
        public String cwid;
        public List<PrimaRoleResponse> primaRoles;
        public List<PrimaSecurityGroupResponse> primaSecurityGroups;
    }

    public class PrimaRoleRequest {
        public String name;
        public String status;

        public PrimaRoleRequest(String name, String status){
            this.name = name;
            this.status = status;
        }
    }

    public class PrimaRoleResponse {
        public String name;
        public String status;
        public String error;
    }

    public class PrimaSecurityGroupRequest {
        public String name;
        public String status;

        public PrimaSecurityGroupRequest(String name, String status){
            this.name = name;
            this.status = status;
        }
    }

    public class PrimaSecurityGroupResponse {
        public String name;
        public String status;
        public String error;
    }
}