force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/CWID__c.field-meta.xml
<CustomField>
    <fullName>CWID__c</fullName>
    <label>CWID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PrimaRequestsInProgressRestApi.cls
@RestResource(urlMapping='/prima/requestsinprogress/*')
global with sharing class PrimaRequestsInProgressRestApi {
    private static final Set<String> STATUSES_TO_UPDATE = new Set<String>{
        UserEntryData.STATUS_ASSIGNED, 
        UserEntryData.STATUS_ERROR
    };

    global class PrimaRequest {
        public List<PrimaData.UserRequest> users;
    }
    
    @HttpGet
    global static PrimaRequest getPrimaRequestsInProgress() {
        PrimaRequest primaRequest = new PrimaRequest();
        primaRequest.users = new List<PrimaData.UserRequest>();
        List<User_Entry__c> userEntries = getLockedUserEntriesWithRolesAndSecurityGroups();
        for(User_Entry__c userEntry : userEntries){
            primaRequest.users.add(new PrimaData.UserRequest(userEntry));
        }
        
        return primaRequest;
    }

    @HttpPost
    global static void updatePrimaRequestsInProgress(List<PrimaData.UserResponse> users) {
        Set<String> cwids = PrimaData.getUserCwids(users);
        Map<String, User_Entry__c> userEntriesByCwid = UserEntryUtils.getUserEntriesByCwid(cwids);

        try {
            updateUserPrimaRoles(users, userEntriesByCwid);
            updateUserPrimaSecurityGroups(users, userEntriesByCwid);
        } catch(Exception ex){
            HandleCustomException.logException(ex);
            RestContext.response.statusCode = 400;
        }
    }

    private static List<User_Entry__c> getLockedUserEntriesWithRolesAndSecurityGroups(){
        List<User_Entry__c> userEntries = new List<User_Entry__c>();
        for(User_Entry__c userEntry : [SELECT CWID__c,
                                              (SELECT Prima_Role__r.Name, Status__c FROM User_Prima_Roles__r 
                                               WHERE Status__c IN :PrimaData.IN_PROGRESS_STATUSES),
                                              (SELECT Prima_Security_Group__r.Name, Status__c FROM User_Prima_Security_Groups__r 
                                               WHERE Status__c IN :PrimaData.IN_PROGRESS_STATUSES)
                                       FROM User_Entry__c WHERE Is_Locked__c = true]){
            if(!userEntry.User_Prima_Roles__r.isEmpty() || !userEntry.User_Prima_Security_Groups__r.isEmpty()){
                userEntries.add(userEntry);
            }
        }
        
        return userEntries;
    }

    private static void updateUserPrimaRoles(List<PrimaData.UserResponse> users, Map<String, User_Entry__c> userEntriesByCwid){
        List<User_Prima_Role__c> userPrimaRolesToUpdate = new List<User_Prima_Role__c>();
        List<User_Prima_Role__c> userPrimaRolesToDelete = new List<User_Prima_Role__c>();

        User_Entry__c userEntry;
        User_Prima_Role__c userPrimaRole;
        for(PrimaData.UserResponse user : users){
            userEntry = userEntriesByCwid.containsKey(user.cwid) ? userEntriesByCwid.get(user.cwid) : null;
            if(userEntry != null && user.primaRoles != null){
                for(PrimaData.PrimaRoleResponse primaRole : user.primaRoles){
                    userPrimaRole = UserEntryUtils.getUserPrimaRoleByName(userEntry, primaRole.name);
                    if(userPrimaRole != null && STATUSES_TO_UPDATE.contains(primaRole.status)){
                        userPrimaRolesToUpdate.add(PrimaData.getUserPrimaRoleToUpdate(userPrimaRole.Id, primaRole));
                    } else if(userPrimaRole != null && primaRole.status == UserEntryData.STATUS_REMOVED){
                        userPrimaRolesToDelete.add(userPrimaRole);
                    }
                }
            }
        }

        update userPrimaRolesToUpdate;
        delete userPrimaRolesToDelete;
    }

    private static void updateUserPrimaSecurityGroups(List<PrimaData.UserResponse> users, Map<String, User_Entry__c> userEntriesByCwid){
        List<User_Prima_Security_Group__c> userPrimaSecurityGroupsToUpdate = new List<User_Prima_Security_Group__c>();
        List<User_Prima_Security_Group__c> userPrimaSecurityGroupsToDelete = new List<User_Prima_Security_Group__c>();

        User_Entry__c userEntry;
        User_Prima_Security_Group__c userPrimaSecurityGroup;
        for(PrimaData.UserResponse user : users){
            userEntry = userEntriesByCwid.containsKey(user.cwid) ? userEntriesByCwid.get(user.cwid) : null;
            if(userEntry != null && user.primaSecurityGroups != null){
                for(PrimaData.PrimaSecurityGroupResponse primaSecurityGroup : user.primaSecurityGroups){
                    userPrimaSecurityGroup = UserEntryUtils.getUserPrimaSecurityGroupByName(userEntry, primaSecurityGroup.name);
                    if(userPrimaSecurityGroup != null && STATUSES_TO_UPDATE.contains(primaSecurityGroup.status)){
                        userPrimaSecurityGroupsToUpdate.add(PrimaData.getUserPrimaSecurityGroupToUpdate(userPrimaSecurityGroup.Id, primaSecurityGroup));
                    } else if(userPrimaSecurityGroup != null && primaSecurityGroup.status == UserEntryData.STATUS_REMOVED){
                        userPrimaSecurityGroupsToDelete.add(userPrimaSecurityGroup);
                    } 
                }
            }
        }
        
        update userPrimaSecurityGroupsToUpdate;
        delete userPrimaSecurityGroupsToDelete;
    }
}