force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Role_Matrix_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix_Type__c</fullName>
    <description>Options in this field will decide the type of Role Matrix to be created i.e. which fields will be required to create a Role Matrix record.</description>
    <label>Role Matrix Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>3-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>2-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>Global Job role/ Add-On role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/Role_Matrix_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Role</label>
    <nameField>
        <displayFormat>Role Matrix PR-{0000}</displayFormat>
        <label>Role Matrix Prima Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/Role_Matrix_Prima_SG__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Security Group</label>
    <nameField>
        <displayFormat>Role Matrix PrimaSG-{0000}</displayFormat>
        <label>Role Matrix Prima Security Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoleMatrixUtils.cls
//Utility class for Role Matrix
//Last modified : 14/03/2023 - Added new logic to return assignments from Role Matrix based on new field- Role Matrix Type
//Added error handling

public class RoleMatrixUtils {
    //Return Role Matrix record based on prvided id
    public static Role_Matrix__c getRoleMatrix(String roleMatrixId){
        Set<String> roleMatrixIds = new Set<String>{roleMatrixId};
            List<Role_Matrix__c> roleMatricesList; 
        try{
            roleMatricesList = getRoleMatrices(roleMatrixIds);    
        }
        catch(Exception e){
            System.debug(HandleCustomException.debugException(e));
        }
        
        if(roleMatricesList.isEmpty()){
            return null;
        }
        return roleMatricesList[0];
    }
    
    
    //Return List of Role Matrices based on set of Role Matrix Ids
    public static List<Role_Matrix__c> getRoleMatrices(Set<String> roleMatrixIds){
        return [SELECT Id, Name, Job_Role__c, MAPV_Department__c,Role_Matrix_Type__c,
                (SELECT Id, MyLearning_Program__c, MyLearning_Program__r.Name FROM Role_Matrix_MyLearning_Programs__r),
                (SELECT Id, Prima_Role__c, Prima_Role__r.Name FROM Role_Matrix_Prima_Roles__r),
                (SELECT Id, Prima_Security_Group__c, Prima_Security_Group__r.Name FROM Role_Matrix_Prima_Security_Groups__r)
                FROM Role_Matrix__c WHERE Id IN :roleMatrixIds];
    }
    
    
    //Return List of Role Matrices based on selection of Job Role, MAPV Dept, Group and Company in User Entry
    public static List<Role_Matrix__c> getRoleMatrices(Set<Id> jobRoleIds, Id mapvDepartmentId, Id mapvGroupId, Id companyId) {
        List<Role_Matrix__c> roleMatrixList = new List<Role_Matrix__c>();
        try{
            for(Id jobRoleId:jobRoleIds ){
                List<Role_Matrix__c> roleMatrixsingleList = new List<Role_Matrix__c>();
                Id mapvDepartmentIds= mapvDepartmentId;
                Id mapvGroupIds= mapvGroupId;
                Id companyIds=companyId;
                roleMatrixsingleList=RoleMatrixUtils.getRoleMatrix(jobRoleId, mapvDepartmentIds, mapvGroupIds, companyIds);
                roleMatrixList.addall(roleMatrixsingleList);
            }
        }
        catch(Exception e){
            System.debug(HandleCustomException.debugException(e));
        }
        
        return roleMatrixList;
    }
    
    //Return a Role Matrix record based on provided input parameters. 
    //Matching logic is based on the prioriry order of Role Matrix Type
    //staring from 4-Criteria Role Matrix(/Global Job role/ Add-On role), 3-Criteria Role Matrix, 2-Criteria Role Matrix
    
    public static List<Role_Matrix__c> getRoleMatrix(Id jobRoleId, Id mapvDepartmentId, Id mapvGroupId, Id companyId){
        List<Role_Matrix__c> roleMatrixList = new List<Role_Matrix__c>();
        roleMatrixList= [SELECT Id, Name, Job_Role__c,Role_Matrix_Type__c,
                         (SELECT Id, MyLearning_Program__c, MyLearning_Program__r.Name FROM Role_Matrix_MyLearning_Programs__r),
                         (SELECT Id, Prima_Role__c, Prima_Role__r.Name FROM Role_Matrix_Prima_Roles__r),
                         (SELECT Id, Prima_Security_Group__c, Prima_Security_Group__r.Name FROM Role_Matrix_Prima_Security_Groups__r)
                         FROM Role_Matrix__c 
                         WHERE Job_Role__c = : jobRoleId
                         AND ( 
                             Role_Matrix_Type__c = 'Global Job role/ Add-On role'
                             OR (
                                 Role_Matrix_Type__c = '4-Criteria Role Matrix'
                                 AND MAPV_Department__c = :mapvDepartmentId
                                 AND MAPV_Group__c = :mapvGroupId
                                 AND Company__c = :companyId
                             )     
                         )
                        ];
        
        
        if(roleMatrixList.size()==0){
            roleMatrixList= [SELECT Id, Name, Job_Role__c,
                             (SELECT Id, MyLearning_Program__c, MyLearning_Program__r.Name FROM Role_Matrix_MyLearning_Programs__r),
                             (SELECT Id, Prima_Role__c, Prima_Role__r.Name FROM Role_Matrix_Prima_Roles__r),
                             (SELECT Id, Prima_Security_Group__c, Prima_Security_Group__r.Name FROM Role_Matrix_Prima_Security_Groups__r)
                             FROM Role_Matrix__c 
                             WHERE Job_Role__c = : jobRoleId
                             AND (
                                 Role_Matrix_Type__c = '3-Criteria Role Matrix'
                                 AND Company__c = :companyId
                                 AND MAPV_Department__c = :mapvDepartmentId
                             )
                            ];
            
            if(roleMatrixList.size()==0){
                roleMatrixList= [SELECT Id, Name, Job_Role__c,
                                 (SELECT Id, MyLearning_Program__c, MyLearning_Program__r.Name FROM Role_Matrix_MyLearning_Programs__r),
                                 (SELECT Id, Prima_Role__c, Prima_Role__r.Name FROM Role_Matrix_Prima_Roles__r),
                                 (SELECT Id, Prima_Security_Group__c, Prima_Security_Group__r.Name FROM Role_Matrix_Prima_Security_Groups__r)
                                 FROM Role_Matrix__c 
                                 WHERE Job_Role__c = : jobRoleId
                                 AND (
                                     Role_Matrix_Type__c = '2-Criteria Role Matrix'
                                     AND Company__c = :companyId	
                                 )
                                ];
                
            }	
        }
        
        return roleMatrixList;
    }
    
}