force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Role_Matrix_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix_Type__c</fullName>
    <description>Options in this field will decide the type of Role Matrix to be created i.e. which fields will be required to create a Role Matrix record.</description>
    <label>Role Matrix Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>3-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>2-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>Global Job role/ Add-On role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/Role_Matrix_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Role</label>
    <nameField>
        <displayFormat>Role Matrix PR-{0000}</displayFormat>
        <label>Role Matrix Prima Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/Role_Matrix_Prima_SG__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Security Group</label>
    <nameField>
        <displayFormat>Role Matrix PrimaSG-{0000}</displayFormat>
        <label>Role Matrix Prima Security Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoleMatrixData.cls
//class to create a data structure used in other classes and lwc component
public class RoleMatrixData {
    
    @AuraEnabled public Id roleMatrixId { get; set; }
    @AuraEnabled public Id jobRoleId { get; set; }
    @AuraEnabled public String roleMatrixType { get; set; }
    @AuraEnabled public List<MyLearning_Program__c> myLearningPrograms { get; set; }
    @AuraEnabled public List<Prima_Role__c> primaRoles { get; set; }
    @AuraEnabled public List<Prima_Security_Group__c> primaSecurityGroups { get; set; }

    public RoleMatrixData() {
        myLearningPrograms = new List<MyLearning_Program__c>();
        primaRoles = new List<Prima_Role__c>();
        primaSecurityGroups = new List<Prima_Security_Group__c>();
    }

    public RoleMatrixData(Role_Matrix__c roleMatrix){
        roleMatrixId = roleMatrix.Id;
        roleMatrixType=roleMatrix.Role_Matrix_Type__c;
        jobRoleId = roleMatrix.Job_Role__c;
        setMyLearningPrograms(roleMatrix.Role_Matrix_MyLearning_Programs__r);
        setPrimaRoles(roleMatrix.Role_Matrix_Prima_Roles__r);
        setPrimaSecurityGroups(roleMatrix.Role_Matrix_Prima_Security_Groups__r);
    }
    
    //Set MyLearning details in Role_Matrix_ML junction object
    private void setMyLearningPrograms(List<Role_Matrix_ML__c> roleMatrixMyLearningPrograms){
        myLearningPrograms = new List<MyLearning_Program__c>();
        for(Role_Matrix_ML__c roleMatrixMyLearningProgram : roleMatrixMyLearningPrograms){
            myLearningPrograms.add(
                new MyLearning_Program__c(
                    Id = roleMatrixMyLearningProgram.MyLearning_Program__c,
                    Name = roleMatrixMyLearningProgram.MyLearning_Program__r.Name
                )
            );
        }
    }
    
    //Set Prima Role details in Role_Matrix_Prima_Role junction object
    private void setPrimaRoles(List<Role_Matrix_Prima_Role__c> roleMatrixPrimaRoles){
        primaRoles = new List<Prima_Role__c>();
        for(Role_Matrix_Prima_Role__c roleMatrixPrimaRole : roleMatrixPrimaRoles){
            primaRoles.add(
                new Prima_Role__c(
                    Id = roleMatrixPrimaRole.Prima_Role__c,
                    Name = roleMatrixPrimaRole.Prima_Role__r.Name
                )
            );
        }
    }
    
    //Set PrimaSecurityGroup details in Role_Matrix_Prima_SG junction object
    private void setPrimaSecurityGroups(List<Role_Matrix_Prima_SG__c> roleMatrixPrimaSecurityGroups){
        primaSecurityGroups = new List<Prima_Security_Group__c>();
        for(Role_Matrix_Prima_SG__c roleMatrixPrimaSecurityGroup : roleMatrixPrimaSecurityGroups){
            primaSecurityGroups.add(
                new Prima_Security_Group__c(
                    Id = roleMatrixPrimaSecurityGroup.Prima_Security_Group__c,
                    Name = roleMatrixPrimaSecurityGroup.Prima_Security_Group__r.Name
                )
            );
        }
    }
}