force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Uma_Company__c.field-meta.xml
<CustomField>
    <fullName>Uma_Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/CWID__c.field-meta.xml
<CustomField>
    <fullName>CWID__c</fullName>
    <label>CWID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Primary_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Manager (R Line)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Entries2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>Staff_Status__c</fullName>
    <label>Staff Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Long-Term Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/User_Time_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Time Tracking</label>
    <nameField>
        <displayFormat>UTTN-{0000}</displayFormat>
        <label>User Time Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Time Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Time_Tracking__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <formula>User_Entry__r.Is_Locked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>Staff_Status__c</fullName>
    <formula>TEXT(User_Entry__r.Staff_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Staff Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Time Trackings</relationshipLabel>
    <relationshipName>User_Time_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accenture</fullName>
    </customValue>
    <customValue>
        <fullName>ARGUS Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Aristo</fullName>
    </customValue>
    <customValue>
        <fullName>Averbis</fullName>
    </customValue>
    <customValue>
        <fullName>BAYER</fullName>
    </customValue>
    <customValue>
        <fullName>Capgemini</fullName>
    </customValue>
    <customValue>
        <fullName>CAPTATIVA</fullName>
    </customValue>
    <customValue>
        <fullName>Cognizant</fullName>
    </customValue>
    <customValue>
        <fullName>EPS</fullName>
    </customValue>
    <customValue>
        <fullName>Genpact Inc</fullName>
    </customValue>
    <customValue>
        <fullName>JNR PV Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Lenolution</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER EXT.</fullName>
    </customValue>
    <customValue>
        <fullName>Pinnaxis</fullName>
    </customValue>
    <customValue>
        <fullName>RxLogic</fullName>
    </customValue>
    <customValue>
        <fullName>Scala</fullName>
    </customValue>
    <customValue>
        <fullName>Syncwork</fullName>
    </customValue>
    <customValue>
        <fullName>TCS (IT)</fullName>
    </customValue>
    <customValue>
        <fullName>TCS (PV)</fullName>
    </customValue>
    <description>Company global value set Used for User Entry, Role Matrix and Hirep</description>
    <masterLabel>Company</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/UserTimeTrackingTriggerHandlerTest.cls
//Test class to cover the UserTimeTrackingTriggerHandler
@isTest
private class UserTimeTrackingTriggerHandlerTest {
	@TestSetup
    private static void setupTestData(){

        Job_Role__c jobRole = TestDataService.getDefaultJobRole();
        insert jobRole;

        MAPV_Department__c mapvDepartment = TestDataService.getDefaultMapvDepartment();
        insert mapvDepartment;

        MAPV_Group__c mapvGroup = TestDataService.getDefaultMapvGroup();
        insert mapvGroup;

        Role_Matrix__c roleMatrix = TestDataService.createRoleMatrix(new Role_Matrix__c(
            Job_Role__c = jobRole.Id,
            MAPV_Department__c = mapvDepartment.Id,
            MAPV_Group__c = mapvGroup.Id
        ));
        insert roleMatrix;
        
        Role_Matrix__c roleMatrix1 = [SELECT Id, Job_Role__c, MAPV_Department__c, MAPV_Group__c, Uma_Company__c FROM Role_Matrix__c LIMIT 1];
        Profile profileRecord = UserUtils.getPlatformEndUserProfile();
        User userRecord = TestDataService.getDefaultUser();
        userRecord.ProfileId = profileRecord.Id;
        insert userRecord;
        User_Entry__c userEntry = (User_Entry__c) TestDataService.createUserEntry(new User_Entry__c(
            CWID__c = 'ABCDE',
            Email__c = 'ABCDE.test@bayer.com',
            Primary_Job_Role__c = roleMatrix1.Job_Role__c,
            MAPV_Department__c = roleMatrix1.MAPV_Department__c,
            MAPV_Group__c = roleMatrix1.MAPV_Group__c,
            Uma_Company__c = roleMatrix1.Uma_Company__c,
            Resource_Manager__c = userRecord.Id
        ));
        insert userEntry;
    
    }
    
    //To test the afterUpdate trigger functionality of UserTT
    @IsTest
    static void updateUserTimeTrackingTest() {
        User_Entry__c userEntry = [SELECT Id, Staff_Status__c, Is_Locked__c FROM User_Entry__c LIMIT 1];
        userEntry.Is_Locked__c = true;
        Update userEntry;
        User_Time_Tracking__c userTTToCreate = (User_Time_Tracking__c) TestDataService.createUserTimeTracking(new User_Time_Tracking__c(
            User_Entry__c = userEntry.Id,
            Status__c = 'Assign',
            Name__c = 'User Time Tracking'
        ));
        
        insert userTTToCreate;
        
        User_Time_Tracking__c userTTToUpdate = [SELECT Id, User_Entry__c, Status__c, Staff_Status__c, Name__c FROM User_Time_Tracking__c LIMIT 1];
        if(userTTToUpdate!=null){
            userTTToUpdate.Status__c = 'Assigned';
        }
        
        Update userTTToUpdate;
        User_Entry__c userEntryRecord = [SELECT Id, Staff_Status__c, Is_Locked__c FROM User_Entry__c LIMIT 1];
        System.assertEquals(false, userEntryRecord.Is_Locked__c);
        
    }
    
    //To test the afterDelete trigger functionality of UserTT
    @IsTest
    static void deleteUserTimeTrackingTest() {
        User_Entry__c userEntry = [SELECT Id, Staff_Status__c, Is_Locked__c FROM User_Entry__c LIMIT 1];
        userEntry.Is_Locked__c = true;
        Update userEntry;
        User_Time_Tracking__c userTTToCreate = (User_Time_Tracking__c) TestDataService.createUserTimeTracking(new User_Time_Tracking__c(
            User_Entry__c = userEntry.Id,
            Status__c = 'Assign',
            Name__c = 'User Time Tracking'
        ));
        
        insert userTTToCreate;
        User_Time_Tracking__c userTTToUpdate = [SELECT Id, User_Entry__c, Status__c, Staff_Status__c, Name__c FROM User_Time_Tracking__c LIMIT 1];
        if(userTTToUpdate!=null){
            userTTToUpdate.Status__c = 'Remove';
        }
        Update userTTToUpdate;
        Delete userTTToUpdate;
        User_Entry__c userEntryRecord = [SELECT Id, Staff_Status__c, Is_Locked__c FROM User_Entry__c LIMIT 1];
        System.assertEquals(false, userEntryRecord.Is_Locked__c);
        
    }
}