force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Main_Role_Add_on__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on__c</fullName>
    <label>Main Role/Add-on</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobRoleUtils.cls
public class JobRoleUtils {
    public static final String ROLE_MAIN = 'Main';
    public static final String ROLE_ADD_ON = 'Add-on';

    public static Job_Role__c getJobRole(String jobRoleId){
        Set<Id> jobRoleIds = new Set<Id>{jobRoleId};
        List<Job_Role__c> jobRoles = getJobRoles(jobRoleIds);

        if(!jobRoles.isEmpty()){
            return jobRoles[0];
        }
        return null;
    }

    public static List<Job_Role__c> getJobRoles(Set<Id> jobRoleIds){
        return [SELECT Id, Main_Role_Add_on__c 
                FROM Job_Role__c WHERE Id IN :jobRoleIds];
    }
}