force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Additional_Role__c/User_Additional_Role__c.object-meta.xml
<CustomObject>
    <label>User Additional Role</label>
    <nameField>
        <displayFormat>UAR-{00000000}</displayFormat>
        <label>User Additional Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Additional Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Additional_Role__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>User Additional Roles</relationshipLabel>
    <relationshipName>User_Additional_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserEntryData.cls
public class UserEntryData {
    public static final String STATUS_ASSIGN = 'Assign';
    public static final String STATUS_REMOVE = 'Remove';
    public static final String STATUS_ASSIGN_REQUESTED = 'Assign Requested';
    public static final String STATUS_REMOVE_REQUESTED = 'Remove Requested';
    public static final String STATUS_ASSIGNED = 'Assigned';
    public static final String STATUS_REMOVED = 'Removed';
    public static final String STATUS_ERROR = 'Error';

    @AuraEnabled public Id userEntryId { get; set; }
    @AuraEnabled public Boolean isLocked { get; set; }
    @AuraEnabled public Boolean isStaffStatusCurrent { get; set; }
    @AuraEnabled public Boolean isStaffStatusLeft { get; set; }
    @AuraEnabled public Boolean isStaffStatusLongTermLeave { get; set; }
    @AuraEnabled public String primaryJobRole { get; set; }
    @AuraEnabled public String primaryJobRoleId { get; set; }
    @AuraEnabled public String MAPVDepartment { get; set; }
    @AuraEnabled public String MAPVDepartmentName { get; set; }
    @AuraEnabled public String MAPVGroup { get; set; }
    @AuraEnabled public String MAPVGroupName { get; set; }
    @AuraEnabled public String company { get; set; }
    @AuraEnabled public String companyName { get; set; }
    @AuraEnabled public String approvalStatus { get; set; }
    @AuraEnabled public String locations { get; set; }
    @AuraEnabled public String timeTrackingRequired { get; set; }
    
    @AuraEnabled public List<Job_Role__c> jobRoles { get; set; }
    @AuraEnabled public List<UserEntryItem> myLearningPrograms { get; set; }
    @AuraEnabled public List<UserEntryItem> primaRoles { get; set; }
    @AuraEnabled public List<UserEntryItem> primaSecurityGroups { get; set; }
    
    public UserEntryData() {
        jobRoles = new List<Job_Role__c>();
        myLearningPrograms = new List<UserEntryItem>();
        primaRoles = new List<UserEntryItem>();
        primaSecurityGroups = new List<UserEntryItem>();
    }

    public Map<Id, UserEntryItem> getMyLearningProgramsMap(){
        return getUserEntryItemsMap(myLearningPrograms);
    }

    public Map<Id, UserEntryItem> getPrimaRolesMap(){
        return getUserEntryItemsMap(primaRoles);
    }

    public Map<Id, UserEntryItem> getPrimaSecurityGroupsMap(){
        return getUserEntryItemsMap(primaSecurityGroups);
    }

    public void setJobRoles(List<User_Additional_Role__c> userAdditionalRoles){
        for(User_Additional_Role__c userAdditionalRole : userAdditionalRoles){
            jobRoles.add(
                new Job_Role__c(
                    Id = userAdditionalRole.Job_Role__c,
                    Name = userAdditionalRole.Job_Role__r.Name
                )
            );
        }
    }

    public void setMyLearningPrograms(List<User_MyLearning_Program__c> userMyLearningPrograms){
        String status;
        for(User_MyLearning_Program__c userMyLearningProgram : userMyLearningPrograms){
            status = isStaffStatusLeft && userMyLearningProgram.Status__c == STATUS_ASSIGNED ? STATUS_REMOVE : userMyLearningProgram.Status__c;
            if(!isStaffStatusLeft || (isStaffStatusLeft && status == STATUS_REMOVE)){
                myLearningPrograms.add(
                    new UserEntryItem(
                        userMyLearningProgram.MyLearning_Program__c,
                        userMyLearningProgram.MyLearning_Program__r.Name,
                        status
                    )
                );
            }
        }
    }

    public void setPrimaRoles(List<User_Prima_Role__c> userPrimaRoles){
        String status;
        for(User_Prima_Role__c userPrimaRole : userPrimaRoles){
            status = isStaffStatusLeft && userPrimaRole.Status__c == STATUS_ASSIGNED ? STATUS_REMOVE : userPrimaRole.Status__c;
            if(!isStaffStatusLeft || (isStaffStatusLeft && status == STATUS_REMOVE)){
                primaRoles.add(
                    new UserEntryItem(
                        userPrimaRole.Prima_Role__c,
                        userPrimaRole.Prima_Role__r.Name,
                        status
                    )
                );
            }
        }
    }

    public void setPrimaSecurityGroups(List<User_Prima_Security_Group__c> userPrimaSecurityGroups){
        String status;
        for(User_Prima_Security_Group__c userPrimaSecurityGroup : userPrimaSecurityGroups){
            status = (isStaffStatusLeft || isStaffStatusLongTermLeave) && userPrimaSecurityGroup.Status__c == STATUS_ASSIGNED ? STATUS_REMOVE : userPrimaSecurityGroup.Status__c;
            status = isStaffStatusLeft && userPrimaSecurityGroup.Status__c == STATUS_ASSIGNED ? STATUS_REMOVE : userPrimaSecurityGroup.Status__c;
            if(!isStaffStatusLeft || (isStaffStatusLeft && status == STATUS_REMOVE)){
                primaSecurityGroups.add(
                    new UserEntryItem(
                        userPrimaSecurityGroup.Prima_Security_Group__c,
                        userPrimaSecurityGroup.Prima_Security_Group__r.Name,
                        status
                    )
                );
            }
        }
    }

    public void addNewMyLearningProgram(Id myLearningProgramId, String myLearningProgramName){
        myLearningPrograms.add(
            new UserEntryItem(myLearningProgramId, myLearningProgramName, STATUS_ASSIGN)
        );
    }

    public void addNewPrimaRole(Id primaRoleId, String primaRoleName){
        primaRoles.add(
            new UserEntryItem(primaRoleId, primaRoleName, STATUS_ASSIGN)
        );
    }

    public void addNewPrimaSecurityGroup(Id primaSecurityGroupId, String primaSecurityGroupName){
        primaSecurityGroups.add(
            new UserEntryItem(primaSecurityGroupId, primaSecurityGroupName, STATUS_ASSIGN)
        );
    }

    public void removeMyLearningPrograms(Set<Id> myLearningProgramIdsToRemove){
        myLearningPrograms = removeUserEntryItems(myLearningPrograms, myLearningProgramIdsToRemove);
    }

    public void removePrimaRoles(Set<Id> primaRoleIdsToRemove){
        primaRoles = removeUserEntryItems(primaRoles, primaRoleIdsToRemove);
    }

    public void removePrimaSecurityGroups(Set<Id> primaSecurityGroupIdsToRemove){
        primaSecurityGroups = removeUserEntryItems(primaSecurityGroups, primaSecurityGroupIdsToRemove);
    }

    private Map<Id, UserEntryItem> getUserEntryItemsMap(List<UserEntryItem> userEntryItems){
        Map<Id, UserEntryItem> userEntryItemsMap = new Map<Id, UserEntryItem>();
        for(UserEntryItem userEntryItem : userEntryItems){
            userEntryItemsMap.put(userEntryItem.id, userEntryItem);
        }
        return userEntryItemsMap;
    }

    private List<UserEntryItem> removeUserEntryItems(List<UserEntryItem> userEntryItems, Set<Id> userEntryItemIdsToRemove){
        List<UserEntryItem> newUserEntryItems = new List<UserEntryItem>();
        for(UserEntryItem userEntryItem : userEntryItems){
            if(!userEntryItemIdsToRemove.contains(userEntryItem.id)){
                newUserEntryItems.add(userEntryItem);
            }
        }
        return newUserEntryItems;
    }

    public class UserEntryItem {
        @AuraEnabled public Id id { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String iconName { get; set; }
        @AuraEnabled public String iconTitle { get; set; }
        @AuraEnabled public String iconVariant { get; set; }

        public UserEntryItem(){}

        public UserEntryItem(Id id, String name, String status){
            this.id = id;
            this.name = name;
            this.status = status;
            setStatus(status);
        }

        public void setStatus(String status){
            this.status = status;
            if(status == STATUS_ASSIGN){
                this.iconName = 'utility:reassign';
                this.iconTitle = Label.ToBeAssigned;
            } else if(status == STATUS_ASSIGNED){
                this.iconName = 'utility:success';
                this.iconTitle = status;
                this.iconVariant = 'success';
            } else if(status == STATUS_REMOVE){
                this.iconName = 'utility:ban';
                this.iconTitle = Label.ToBeRemoved;
                this.iconVariant = 'error';
            }
        }
    }

}