force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Main_Role_Add_on__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on__c</fullName>
    <label>Main Role/Add-on</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Main_Role_Add_on_Formula__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on_Formula__c</fullName>
    <formula>TEXT(Job_Role__r.Main_Role_Add_on__c)</formula>
    <label>Main Role/Add-on Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Role_Matrix_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix_Type__c</fullName>
    <description>Options in this field will decide the type of Role Matrix to be created i.e. which fields will be required to create a Role Matrix record.</description>
    <label>Role Matrix Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>3-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>2-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>Global Job role/ Add-On role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoleMatrixControllerTest.cls
/*
* Description: Test class for RoleMatrixController class.
*/
@isTest
private class RoleMatrixControllerTest {
    @TestSetup
    private static void createTestData() {
        Job_Role__c jobRole1 = TestDataService.getDefaultJobRole();
        insert jobRole1;
        
        Job_Role__c jobRole2 = TestDataService.getDefaultJobRole();
        jobRole2.Name='Test Job Role1';
        insert jobRole2;
        
        Job_Role__c jobRole3 = TestDataService.getDefaultJobRole();
        jobRole3.Name='Test Global Job Role';
        jobRole3.Main_Role_Add_on__c='Add-on';
        insert jobRole3;
        
        
        MAPV_Department__c department1 = TestDataService.getDefaultMapvDepartment();
        insert department1;
        
        MAPV_Group__c group1 = TestDataService.getDefaultMapvGroup();
        insert group1;
        
        Account acc1= TestDataService.getDefaultAccount();
        insert acc1;
        
        MyLearning_Program__c myLearnings = TestDataService.getDefaultMyLearningProgram();
        insert myLearnings;
        
        Role_Matrix__c roleMatrix1= TestDataService.getDefaultRoleMatrix();
        roleMatrix1.Job_Role__c = [Select Id from Job_Role__c][0].Id;
        roleMatrix1.Role_Matrix_Type__c='4-Criteria Role Matrix';
        roleMatrix1.MAPV_Department__c = [Select Id from MAPV_Department__c][0].Id;
        roleMatrix1.MAPV_Group__c = [Select Id from MAPV_Group__c][0].Id;
        roleMatrix1.Company__c = [Select Id from Account][0].Id;
        insert roleMatrix1;
        
        Role_Matrix_ML__c roleMatrix_MyLearning = new Role_Matrix_ML__c();
        roleMatrix_MyLearning.Role_Matrix__c = roleMatrix1.Id;
        roleMatrix_MyLearning.MyLearning_Program__c = myLearnings.Id;
        insert roleMatrix_MyLearning;
        
        Role_Matrix__c roleMatrix_3_criteria= TestDataService.getDefaultRoleMatrix();
        roleMatrix_3_criteria.Job_Role__c = [Select Id from Job_Role__c where Name=:'Test Job Role1'].Id;
        roleMatrix_3_criteria.Role_Matrix_Type__c='3-Criteria Role Matrix';
        roleMatrix_3_criteria.MAPV_Department__c = [Select Id from MAPV_Department__c][0].Id;
        roleMatrix_3_criteria.Company__c = [Select Id from Account][0].Id;
        insert roleMatrix_3_criteria;
        Role_Matrix_ML__c roleMatrix_MyLearning_3_criteria = new Role_Matrix_ML__c();
        roleMatrix_MyLearning_3_criteria.Role_Matrix__c = roleMatrix_3_criteria.Id;
        roleMatrix_MyLearning_3_criteria.MyLearning_Program__c = myLearnings.Id;
        insert roleMatrix_MyLearning_3_criteria;
        
        Role_Matrix__c roleMatrixGlobalJob= TestDataService.getDefaultRoleMatrix();
        roleMatrixGlobalJob.Job_Role__c = [Select Id from Job_Role__c where Main_Role_Add_on__c='Add-on'][0].Id;
        roleMatrixGlobalJob.Role_Matrix_Type__c='Global Job role/ Add-On role';
        insert roleMatrixGlobalJob;
        Role_Matrix_ML__c roleMatrix_MyLearningGlobalJob = new Role_Matrix_ML__c();
        roleMatrix_MyLearningGlobalJob.Role_Matrix__c = roleMatrixGlobalJob.Id;
        roleMatrix_MyLearningGlobalJob.MyLearning_Program__c = myLearnings.Id;
        insert roleMatrix_MyLearningGlobalJob;
    }
    
    //Test the functionality to display all the Role Matrices Records / filtered records based on search text in Role Matrix Overview tab
    @IsTest
    private static void testName() {
        Test.startTest();
        RoleMatrixListWrapper wrapperList = new RoleMatrixListWrapper();
        wrapperList.roleMatrixRecord = RoleMatrixController.getFilteredRoleMatrixDetails('')[0].roleMatrixRecord;
        wrapperList.myLearningString = RoleMatrixController.getFilteredRoleMatrixDetails('')[0].myLearningString;
        system.assertEquals(wrapperList.roleMatrixRecord.Main_Role_Add_on_Formula__c, JobRoleUtils.ROLE_MAIN);
        system.assertEquals(wrapperList.myLearningString, 'Test ML Program');
        RoleMatrixListWrapper wrapperList1 = new RoleMatrixListWrapper();
        wrapperList1.roleMatrixRecord = RoleMatrixController.getFilteredRoleMatrixDetails('Group')[0].roleMatrixRecord;
        system.assertEquals(wrapperList1.roleMatrixRecord.MAPV_Group__r.Name, 'Test Group');
        Test.stopTest();
        
    }
    
    public class RoleMatrixListWrapper{
        @AuraEnabled
        public Role_Matrix__c roleMatrixRecord{get;set;}
        @AuraEnabled
        public String myLearningString{get;set;}
        @AuraEnabled
        public String primaRoleString{get;set;}
        @AuraEnabled
        public String primaSecurityGroupString{get;set;}
        
    }
    
}