force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Main_Role_Add_on_Formula__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on_Formula__c</fullName>
    <formula>TEXT(Job_Role__r.Main_Role_Add_on__c)</formula>
    <label>Main Role/Add-on Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Role_Matrix_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix_Type__c</fullName>
    <description>Options in this field will decide the type of Role Matrix to be created i.e. which fields will be required to create a Role Matrix record.</description>
    <label>Role Matrix Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>3-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>2-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>Global Job role/ Add-On role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Uma_Company__c.field-meta.xml
<CustomField>
    <fullName>Uma_Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/Role_Matrix_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Role</label>
    <nameField>
        <displayFormat>Role Matrix PR-{0000}</displayFormat>
        <label>Role Matrix Prima Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/Role_Matrix_Prima_SG__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Security Group</label>
    <nameField>
        <displayFormat>Role Matrix PrimaSG-{0000}</displayFormat>
        <label>Role Matrix Prima Security Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Company.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accenture</fullName>
    </customValue>
    <customValue>
        <fullName>ARGUS Consult</fullName>
    </customValue>
    <customValue>
        <fullName>Aristo</fullName>
    </customValue>
    <customValue>
        <fullName>Averbis</fullName>
    </customValue>
    <customValue>
        <fullName>BAYER</fullName>
    </customValue>
    <customValue>
        <fullName>Capgemini</fullName>
    </customValue>
    <customValue>
        <fullName>CAPTATIVA</fullName>
    </customValue>
    <customValue>
        <fullName>Cognizant</fullName>
    </customValue>
    <customValue>
        <fullName>EPS</fullName>
    </customValue>
    <customValue>
        <fullName>Genpact Inc</fullName>
    </customValue>
    <customValue>
        <fullName>JNR PV Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Lenolution</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER EXT.</fullName>
    </customValue>
    <customValue>
        <fullName>Pinnaxis</fullName>
    </customValue>
    <customValue>
        <fullName>RxLogic</fullName>
    </customValue>
    <customValue>
        <fullName>Scala</fullName>
    </customValue>
    <customValue>
        <fullName>Syncwork</fullName>
    </customValue>
    <customValue>
        <fullName>TCS (IT)</fullName>
    </customValue>
    <customValue>
        <fullName>TCS (PV)</fullName>
    </customValue>
    <description>Company global value set Used for User Entry, Role Matrix and Hirep</description>
    <masterLabel>Company</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/RoleMatrixController.cls
/**********************************************************
*  RoleMatrixController
* 
*  Author: Sachin Chothe
*  Created Date: 15/11/2021
*  Last Modified By: -
*  Last Modified Date: -14/03/2023
* 
*  Description: controller class for Lightning Web Component - 'RoleMatrixDisplay'.
*  //Added error handling
*
* *********************************************************/

public class RoleMatrixController{
    //method to get filtered Role Matrix records based on search key
    @AuraEnabled(cacheable=true)
    public static List<RoleMatrixListWrapper> getFilteredRoleMatrixDetails(String searchKey){
        List<RoleMatrixListWrapper> rolematrixlist ;
        try{
            String query = 'SELECT Id, Role_Matrix_Type__c,Job_Role__r.Name,MAPV_Department__r.Name,MAPV_Group__r.Name,Main_Role_Add_on_Formula__c,Uma_Company__c,Comments__c,(SELECT MyLearning_Program__r.Name From Role_Matrix_MyLearning_Programs__r),(SELECT Prima_Role__r.Name From Role_Matrix_Prima_Roles__r),(SELECT Prima_Security_Group__r.Name From Role_Matrix_Prima_Security_Groups__r) FROM Role_Matrix__c';
            if (searchKey != null && searchKey != '' ) {
                String key = '%' + searchKey + '%';
                query += ' WHERE Job_Role__r.Name LIKE :key OR MAPV_Department__r.Name LIKE :key OR MAPV_Group__r.Name LIKE :key OR Main_Role_Add_on_Formula__c LIKE :key OR Uma_Company__c LIKE :key ORDER BY LastModifiedDate DESC';
                
            }
            else{
                query+=' ORDER BY LastModifiedDate DESC';
            }
            
            rolematrixlist=getRoleMatrixWrapperList(Database.query(query)); 
        }catch (Exception e){
            System.debug(HandleCustomException.debugException(e));
        }
        return rolematrixlist;
    }
    
    // Returns wrapper list RoleMatrixListWrapper with Role Matrix Record and related assignements
    public static List<RoleMatrixListWrapper> getRoleMatrixWrapperList(List<Role_Matrix__c> roleMatrixList){
        List<RoleMatrixListWrapper> roleMatrixWrapperList = new List<RoleMatrixListWrapper>();
        if(!roleMatrixList.isEmpty()){
            for(Role_Matrix__c row : roleMatrixList){
                RoleMatrixListWrapper roleMatrixWrapper = new RoleMatrixListWrapper();
                roleMatrixWrapper.roleMatrixRecord = row;
                Set<String> tempMyLearningSet = new Set<String>();
                Set<String> tempPrimaRoleSet = new Set<String>();
                Set<String> tempPrimaSecurityGroupSet = new Set<String>();
                
                for(Role_Matrix_ML__c index : row.Role_Matrix_MyLearning_Programs__r){
                    tempMyLearningSet.add(index.MyLearning_Program__r.Name);
                }
                roleMatrixWrapper.myLearningString = tempMyLearningSet.toString().substring(1,tempMyLearningSet.toString().length()-1);
                
                for(Role_Matrix_Prima_Role__c index : row.Role_Matrix_Prima_Roles__r){
                    tempPrimaRoleSet.add(index.Prima_Role__r.Name);
                }
                roleMatrixWrapper.primaRoleString = tempPrimaRoleSet.toString().substring(1,tempPrimaRoleSet.toString().length()-1);
                
                for(Role_Matrix_Prima_SG__c index : row.Role_Matrix_Prima_Security_Groups__r){
                    tempPrimaSecurityGroupSet.add(index.Prima_Security_Group__r.Name);
                }
                roleMatrixWrapper.primaSecurityGroupString = tempPrimaSecurityGroupSet.toString().substring(1,tempPrimaSecurityGroupSet.toString().length()-1);
                
                roleMatrixWrapperList.add(roleMatrixWrapper);
            }
        }
        return roleMatrixWrapperList;
    }
    
    //wrapper class to get structured data in LWC
    public class RoleMatrixListWrapper{
        @AuraEnabled
        public Role_Matrix__c roleMatrixRecord{get;set;}
        @AuraEnabled
        public String myLearningString{get;set;}
        @AuraEnabled
        public String primaRoleString{get;set;}
        @AuraEnabled
        public String primaSecurityGroupString{get;set;}
        
    }
}