force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <description>Main object of Donations application. Used to store the details about donation request.</description>
    <label>Donation</label>
    <nameField>
        <label>Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Focus_Area__c.field-meta.xml
<CustomField>
    <fullName>Focus_Area__c</fullName>
    <label>Focus Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Health for all - Child Health</fullName>
            </value>
            <value>
                <fullName>Health for all - Reproductive Health (Contraception)</fullName>
            </value>
            <value>
                <fullName>Health for all - Self care and access to health programs for vulnerable groups in LMIC</fullName>
            </value>
            <value>
                <fullName>Health for all - Public Health</fullName>
            </value>
            <value>
                <fullName>Climate Change</fullName>
            </value>
            <value>
                <fullName>Biodiversity</fullName>
            </value>
            <value>
                <fullName>Water Management</fullName>
            </value>
            <value>
                <fullName>Waste Management</fullName>
            </value>
            <value>
                <fullName>Hunger for none - Food security, food loss, food quality</fullName>
            </value>
            <value>
                <fullName>Hunger for none - Food availability (vulnerable groups)</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Support of frontier research in the life sciences, data science and environmental sciences</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Development of science talents</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Supporting education programs in the Life Sciences, environmental science and data science</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Science and Society</fullName>
            </value>
            <value>
                <fullName>Others (Exceptional)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <label>Organization Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>HCO</fullName>
            </value>
            <value>
                <fullName>Med. Institute</fullName>
            </value>
            <value>
                <fullName>Health Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Overall_Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Overall_Net_Amount__c</fullName>
    <label>Overall Net Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Mr. and Mrs.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Wait for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_History__c/Record_History__c.object-meta.xml
<CustomObject>
    <description>Custom history tracking of objects fields and related objects</description>
    <label>Record History</label>
    <nameField>
        <displayFormat>RH-{0000000}</displayFormat>
        <label>Record History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Updated</fullName>
            </value>
            <value>
                <fullName>Related Record Created</fullName>
            </value>
            <value>
                <fullName>Related Record Field Updated</fullName>
            </value>
            <value>
                <fullName>Related Record Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donation</label>
    <referenceTo>Donation__c</referenceTo>
    <relationshipLabel>Record History</relationshipLabel>
    <relationshipName>Record_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Original_Value__c.field-meta.xml
<CustomField>
    <fullName>Original_Value__c</fullName>
    <label>Original Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Record_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BV-PH-GUOP</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-GUOC</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-VU</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-GUC</fullName>
    </customValue>
    <customValue>
        <fullName>JPH-WH</fullName>
    </customValue>
    <customValue>
        <fullName>BV-CH</fullName>
    </customValue>
    <customValue>
        <fullName>BV-CH-GERM</fullName>
    </customValue>
    <description>Business Unit is used in Donation and Approval Configuration</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonationService.cls
/**********************************************************
*  DonationService
* 
*  Created Date: - 10/30/2023
* 
*  Description: Service class for Donation
*  
* *********************************************************/
public class DonationService {
	public static final String ACTION_FIELD_UPDATE = 'Field Updated';    
    
    public static void createRecordHistoryOnDonationUpdate(Map<Id, Donation__c> newDonations, Map<Id, Donation__c> oldDonationMap){
        List<Record_History__c> recordHistoryList = new List<Record_History__c>();
        for (Donation__c newDonation :newDonations.values()) {
            
            //Track Status__c field
            if (newDonation.Status__c != oldDonationMap.get(newDonation.Id).Status__c){
                addRecordHstoryList(recordHistoryList, 'Status', oldDonationMap.get(newDonation.Id).Status__c, newDonation.Status__c, newDonation.Id);
            }
            //Track Overall_Net_Amount__c field
            if (newDonation.Overall_Net_Amount__c != oldDonationMap.get(newDonation.Id).Overall_Net_Amount__c){
                addRecordHstoryList(recordHistoryList, 'Overall NetAmount', String.valueOf(oldDonationMap.get(newDonation.Id).Overall_Net_Amount__c)+'€', String.valueOf(newDonation.Overall_Net_Amount__c)+'€', newDonation.Id);
            }
            //Track Organization_Type__c field
            if (newDonation.Organization_Type__c != oldDonationMap.get(newDonation.Id).Organization_Type__c){
                addRecordHstoryList(recordHistoryList, 'Organization Type', oldDonationMap.get(newDonation.Id).Organization_Type__c, newDonation.Organization_Type__c, newDonation.Id);
            }
            //Track Focus_Area__c field
            if (newDonation.Focus_Area__c != oldDonationMap.get(newDonation.Id).Focus_Area__c){
                addRecordHstoryList(recordHistoryList, 'Focus Area', oldDonationMap.get(newDonation.Id).Focus_Area__c, newDonation.Focus_Area__c, newDonation.Id);
            }
            //Track Salutation__c field
            if (newDonation.Salutation__c != oldDonationMap.get(newDonation.Id).Salutation__c){
                addRecordHstoryList(recordHistoryList, 'Salutation', oldDonationMap.get(newDonation.Id).Salutation__c, newDonation.Salutation__c, newDonation.Id);
            }
            //Track Contact_First_Name__c field
           if (newDonation.Contact_First_Name__c != oldDonationMap.get(newDonation.Id).Contact_First_Name__c){
                addRecordHstoryList(recordHistoryList, 'Contact FirstName', oldDonationMap.get(newDonation.Id).Contact_First_Name__c, newDonation.Contact_First_Name__c, newDonation.Id);
            }
            //Track Contact_Last_Name__c field
            if (newDonation.Contact_Last_Name__c != oldDonationMap.get(newDonation.Id).Contact_Last_Name__c){
                addRecordHstoryList(recordHistoryList, 'Contact LastName', oldDonationMap.get(newDonation.Id).Contact_Last_Name__c, newDonation.Contact_Last_Name__c, newDonation.Id);
            }
            //Track Contact_Email__c field
            if (newDonation.Contact_Email__c != oldDonationMap.get(newDonation.Id).Contact_Email__c){
                addRecordHstoryList(recordHistoryList, 'Contact Email', oldDonationMap.get(newDonation.Id).Contact_Email__c, newDonation.Contact_Email__c, newDonation.Id);
            }
            //Track Bank__c field
            if (newDonation.Bank__c != oldDonationMap.get(newDonation.Id).Bank__c){
                addRecordHstoryList(recordHistoryList, 'Bank', oldDonationMap.get(newDonation.Id).Bank__c, newDonation.Bank__c, newDonation.Id);
            }
            //Track IBAN__c field
            if (newDonation.IBAN__c != oldDonationMap.get(newDonation.Id).IBAN__c){
                addRecordHstoryList(recordHistoryList, 'IBAN', oldDonationMap.get(newDonation.Id).IBAN__c, newDonation.IBAN__c, newDonation.Id);
            }
            //Track Requestor__c field
            if (newDonation.Requestor__c != oldDonationMap.get(newDonation.Id).Requestor__c){
                addRecordHstoryList(recordHistoryList, 'Requestor', UserUtils.getUserById(oldDonationMap.get(newDonation.Id).Requestor__c)?.Name , UserUtils.getUserById(newDonation.Requestor__c)?.Name, newDonation.Id);
            }
            //Track Account__c field
            if (newDonation.Account__c != oldDonationMap.get(newDonation.Id).Account__c){
                system.debug('@@DonationService.createRecordHistoryOnDonationUpdate> Account= '+ AccountUtils.getAccountById(oldDonationMap.get(newDonation.Id).Account__c));
                addRecordHstoryList(recordHistoryList, 'Account', AccountUtils.getAccountById(oldDonationMap.get(newDonation.Id).Account__c)?.Name , AccountUtils.getAccountById(newDonation.Account__c)?.Name, newDonation.Id);
            }
            //Track Business_Unit__c field
            if (newDonation.Business_Unit__c != oldDonationMap.get(newDonation.Id).Business_Unit__c){
                addRecordHstoryList(recordHistoryList, 'Business Unit', oldDonationMap.get(newDonation.Id).Business_Unit__c, newDonation.Business_Unit__c, newDonation.Id);
            }
           
        }
        
        system.debug('@@DonationService.createRecordHistoryOnDonationUpdate> recordHistoryList= '+ recordHistoryList);
        //Insert Record_History__c records related to Donation
         if (!recordHistoryList.isEmpty()) {
              insert recordHistoryList;
         }
        
    }
    
    //Adds a new record to a Record History list
    private static List<Record_History__c> addRecordHstoryList(List<Record_History__c> recordHistoryList, String fieldToTrack, String oldValue, String newValue, Id donationId){
        recordHistoryList.add(new Record_History__c(
                    Action__c = ACTION_FIELD_UPDATE, 
                    Field__c= fieldToTrack,
                    Original_Value__c = oldValue, 
                    New_Value__c = newValue,
                    User__c = UserInfo.getUserId(),
                    Date__c = System.now(),
                    Donation__c = donationId
                ));
        
         return recordHistoryList;
    }
    
  

 
    
}