force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <formula>User_Entry__r.Is_Locked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserMyLearningProgramUtils.cls
public class UserMyLearningProgramUtils {
    public static final String STATUS_REMOVE = 'Remove';
    
    public static void validateUserMyLearningProgramsOnDelete(Map<Id, User_MyLearning_Program__c> oldUserMyLearningPrograms) {
        Boolean isToBeRemoved;
        for(User_MyLearning_Program__c userMyLearningProgram : oldUserMyLearningPrograms.values()){
            isToBeRemoved = STATUS_REMOVE.equals(userMyLearningProgram.Status__c);
            if(userMyLearningProgram.Is_Locked__c && !isToBeRemoved){
                userMyLearningProgram.addError(Label.UserMyLearningProgramCannotBeDeleted);
            }
        }
    }
}