force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserPrimaRoleUtils.cls
public class UserPrimaRoleUtils {
    public static final String STATUS_ASSIGN = 'Assign';
    public static final String STATUS_REMOVE = 'Remove';
    public static final String STATUS_ERROR = 'Error';
    public static final Set<String> UPDATABLE_STATUSES = new Set<String>{
        STATUS_ASSIGN,
        STATUS_REMOVE,
        STATUS_ERROR
    };
    
    public static void validateUserPrimaRolesOnDelete(Map<Id, User_Prima_Role__c> oldUserPrimaRoles) {
        Boolean hasDeleteAllPrimaItems = FeatureManagement.checkPermission('DeleteAllPrimaItems');
        Boolean isUpdatable;
        for(User_Prima_Role__c userPrimaRole : oldUserPrimaRoles.values()){
            isUpdatable = UPDATABLE_STATUSES.contains(userPrimaRole.Status__c);
            if(!hasDeleteAllPrimaItems && !isUpdatable){
                userPrimaRole.addError(Label.UserPrimaRoleCannotBeDeleted);
            }
        }
    }
}