force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Primary_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Resource_Manager__c.field-meta.xml
<CustomField>
    <fullName>Resource_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Manager (R Line)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Entries2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserEntryControllerTest.cls
//Test class to cover UserEntryController & UMAHomePageController
@isTest
private class UserEntryControllerTest {
    
    @TestSetup
    private static void setupTestData(){
        Profile platformEndUserProfile = UserUtils.getPlatformEndUserProfile();
        User manager = TestDataService.createUser(new User(
            Username = 'test.manager.ext@bayer.com',
            ProfileId = platformEndUserProfile.Id,
            FederationIdentifier = 'AABBB'
        ));
        insert manager;

        Account company = TestDataService.getDefaultAccount();
        insert company;

        MAPV_Department__c mapvDepartment = TestDataService.getDefaultMapvDepartment();
        insert mapvDepartment;

        MAPV_Group__c mapvGroup = TestDataService.getDefaultMapvGroup();
        insert mapvGroup;

        Job_Role__c jobRole = TestDataService.getDefaultJobRole();
        insert jobRole;

        MyLearning_Program__c myLearningProgram = TestDataService.getDefaultMyLearningProgram();
        insert myLearningProgram;

        Prima_Role__c primaRole = TestDataService.getDefaultPrimaRole();
        insert primaRole;

        Prima_Security_Group__c primaSecurityGroup = TestDataService.getDefaultPrimaSecurityGroup();
        insert primaSecurityGroup;
        
        Role_Matrix__c roleMatrix = TestDataService.createRoleMatrix(new Role_Matrix__c(
            Job_Role__c = jobRole.Id,
            MAPV_Department__c = mapvDepartment.Id,
            MAPV_Group__c = mapvGroup.Id,
            Company__c = company.Id
        ));
        insert roleMatrix;
        
        Role_Matrix_ML__c rmmlp = new Role_Matrix_ML__c(
            Role_Matrix__c = roleMatrix.Id,
            MyLearning_Program__c = myLearningProgram.Id
        );
        insert rmmlp;

        User_Entry__c userEntry = TestDataService.createUserEntry(new User_Entry__c(
            Resource_Manager__c = manager.Id,
            Company__c = company.Id, 
            MAPV_Department__c = mapvDepartment.Id, 
            MAPV_Group__c = mapvGroup.Id, 
            Primary_Job_Role__c = jobRole.Id
        ));
        insert userEntry;
    
        insert new User_MyLearning_Program__c(
            User_Entry__c = userEntry.Id,
            MyLearning_Program__c = myLearningProgram.Id,
            Status__c = UserEntryData.STATUS_ASSIGNED
        );
        insert new User_Prima_Role__c(
            User_Entry__c = userEntry.Id,
            Prima_Role__c = primaRole.Id,
            Status__c = UserEntryData.STATUS_ASSIGNED
        );
        insert new User_Prima_Security_Group__c(
            User_Entry__c = userEntry.Id,
            Prima_Security_Group__c = primaSecurityGroup.Id,
            Status__c = UserEntryData.STATUS_ASSIGNED
        );
    }

    @isTest
    public static void testUserEntryNeedApproval() {
        User manager = [SELECT Id FROM User WHERE Username = 'test.manager.ext@bayer.com'];
        User_Entry__c userEntry = [SELECT Id FROM User_Entry__c LIMIT 1];

        Test.startTest();
		List<User_Entry__c> userEntries = UMAHomePageController.getUserEntryDetails();
        List<User_Entry__c> filteredUserEntries = UMAHomePageController.getFilteredUserEntryDetails('test', '', '');
        System.assertEquals(true, userEntries.size()>0);
        System.assertEquals(true, filteredUserEntries.size()>0);
        System.runAs(manager){
            Boolean result = UserEntryController.doesUserEntryNeedApproval(userEntry.Id);
            System.assertEquals(false, result);
        }

        Test.stopTest();
    }
}