force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Primary_Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>User Entries</relationshipLabel>
    <relationshipName>User_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PrimaNewRequestsRestApiTest.cls
@isTest
public class PrimaNewRequestsRestApiTest {
    @TestSetup
    static void setupTestData() {
        Account company = TestDataService.getDefaultAccount();
        insert company;

        Job_Role__c jobRole = TestDataService.getDefaultJobRole();
        insert jobRole;

        MAPV_Department__c mapvDepartment = TestDataService.getDefaultMapvDepartment();
        insert mapvDepartment;

        MAPV_Group__c mapvGroup = TestDataService.getDefaultMapvGroup();
        insert mapvGroup;
        
        MyLearning_Program__c mlp = TestDataService.getDefaultMyLearningProgram();
        mlp.ID__c = 'PH_RD_170';
        mlp.Name = 'Test ML Program3';
        insert mlp;

        Role_Matrix__c roleMatrix = TestDataService.createRoleMatrix(new Role_Matrix__c(
            Job_Role__c = jobRole.Id,
            MAPV_Department__c = mapvDepartment.Id,
            MAPV_Group__c = mapvGroup.Id,
            Company__c = company.Id
        ));
        insert roleMatrix;
        
       Role_Matrix_ML__c rmmlp = new Role_Matrix_ML__c(
            							MyLearning_Program__c = mlp.Id,
            							Role_Matrix__c = roleMatrix.Id
        						  );
       insert rmmlp;
        
    }

    @isTest
    static void testGetPrimaNewRequests() {
        Role_Matrix__c roleMatrix = [SELECT Id, Job_Role__c, MAPV_Department__c, MAPV_Group__c, Company__c FROM Role_Matrix__c LIMIT 1];
        User_Entry__c ue = (User_Entry__c) TestDataService.createUserEntry(new User_Entry__c(
            Primary_Job_Role__c = roleMatrix.Job_Role__c,
            MAPV_Department__c = roleMatrix.MAPV_Department__c,
            MAPV_Group__c = roleMatrix.MAPV_Group__c,
            Company__c = roleMatrix.Company__c
        ));
        insert ue;

        Test.startTest();
        PrimaNewRequestsRestApi.PrimaRequest req = PrimaNewRequestsRestApi.getPrimaNewRequests();
        Test.stopTest();

        System.assertEquals(true, req != null, 'Request should exist.');
    }

    @isTest
    static void testUpdatePrimaNewRequests() {
        Role_Matrix__c roleMatrix = [SELECT Id, Job_Role__c, MAPV_Department__c, MAPV_Group__c, Company__c FROM Role_Matrix__c LIMIT 1];

        User_Entry__c ue = (User_Entry__c) TestDataService.createUserEntry(new User_Entry__c(
            Primary_Job_Role__c = roleMatrix.Job_Role__c,
            MAPV_Department__c = roleMatrix.MAPV_Department__c,
            MAPV_Group__c = roleMatrix.MAPV_Group__c,
            Company__c = roleMatrix.Company__c
        ));
        insert ue;

        Prima_Role__c pr = TestDataService.getDefaultPrimaRole();
        insert pr;

        User_Prima_Role__c upr = new User_Prima_Role__c(
            User_Entry__c = ue.Id,
            Prima_Role__c = pr.Id,
            Status__c = 'Assign Requested'
        );
        insert upr;

        Prima_Security_Group__c psg = TestDataService.getDefaultPrimaSecurityGroup();
        insert psg;

        User_Prima_Security_Group__c upsg = new User_Prima_Security_Group__c(
            User_Entry__c = ue.Id,
            Prima_Security_Group__c = psg.Id,
            Status__c = 'Assign Requested'
        );
        insert upsg;

        PrimaData.PrimaRoleResponse prrSuccess = new PrimaData.PrimaRoleResponse();
        prrSuccess.name = 'Test Prima Role';
        prrSuccess.status = 'Assign Requested';
        prrSuccess.error = '';

        PrimaData.PrimaSecurityGroupResponse psgrSuccess = new PrimaData.PrimaSecurityGroupResponse();
        psgrSuccess.name = 'Test Prima Security Group';
        psgrSuccess.status = 'Assign Requested';
        psgrSuccess.error = '';

        PrimaData.PrimaRoleResponse prrError = new PrimaData.PrimaRoleResponse();
        prrError.name = 'Test Prima Role';
        prrError.status = 'Error';
        prrError.error = 'Error';

        PrimaData.PrimaSecurityGroupResponse psgrError = new PrimaData.PrimaSecurityGroupResponse();
        psgrError.name = 'Test Prima Security Group';
        psgrError.status = 'Error';
        psgrError.error = 'Error';

        PrimaData.UserResponse urSuccess = new PrimaData.UserResponse();
        urSuccess.cwid = 'BYXXF';
        urSuccess.primaRoles = new List<PrimaData.PrimaRoleResponse>{ prrSuccess };
        urSuccess.primaSecurityGroups = new List<PrimaData.PrimaSecurityGroupResponse>{ psgrSuccess };

        PrimaData.UserResponse urError = new PrimaData.UserResponse();
        urError.cwid = 'BYXXF';
        urError.primaRoles = new List<PrimaData.PrimaRoleResponse>{ prrError };
        urError.primaSecurityGroups = new List<PrimaData.PrimaSecurityGroupResponse>{ psgrError };

        Test.startTest();

        PrimaData.UserRequest ur = new PrimaData.UserRequest(ue);
        PrimaData.PrimaRoleRequest prr = new PrimaData.PrimaRoleRequest(prrSuccess.name, prrSuccess.status);
        PrimaData.PrimaSecurityGroupRequest psgr = new PrimaData.PrimaSecurityGroupRequest(psgrSuccess.name, psgrSuccess.status);

        PrimaNewRequestsRestApi.updatePrimaNewRequests(new List<PrimaData.UserResponse>{ urSuccess });
        PrimaNewRequestsRestApi.updatePrimaNewRequests(new List<PrimaData.UserResponse>{ urError });

        Test.stopTest();

        List<User_Prima_Role__c> resultUprs = [SELECT Id FROM User_Prima_Role__c];
        List<User_Prima_Security_Group__c> resultUpsgs = [SELECT Id FROM User_Prima_Security_Group__c];

        System.assertEquals(1, resultUprs.size(), 'User Prima Roles should be updated.');
        System.assertEquals(1, resultUpsgs.size(), 'User Prima Security Groups should be updated.');
    }
}