force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Main_Role_Add_on__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on__c</fullName>
    <label>Main Role/Add-on</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MAPV_Department__c/MAPV_Department__c.object-meta.xml
<CustomObject>
    <label>MAPV Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Department</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MAPV_Group__c/MAPV_Group__c.object-meta.xml
<CustomObject>
    <label>MAPV Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MAPV Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Department__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Department</label>
    <referenceTo>MAPV_Department__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/MAPV_Group__c.field-meta.xml
<CustomField>
    <fullName>MAPV_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MAPV Group</label>
    <referenceTo>MAPV_Group__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/fields/Role_Matrix_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix_Type__c</fullName>
    <description>Options in this field will decide the type of Role Matrix to be created i.e. which fields will be required to create a Role Matrix record.</description>
    <label>Role Matrix Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>3-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>2-Criteria Role Matrix</fullName>
            </value>
            <value>
                <fullName>Global Job role/ Add-On role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/Role_Matrix_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Role</label>
    <nameField>
        <displayFormat>Role Matrix PR-{0000}</displayFormat>
        <label>Role Matrix Prima Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/Role_Matrix_Prima_SG__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Security Group</label>
    <nameField>
        <displayFormat>Role Matrix PrimaSG-{0000}</displayFormat>
        <label>Role Matrix Prima Security Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoleMatrixServiceTest.cls
//Test the functionality of RoleMatrixService class
@isTest
private class RoleMatrixServiceTest {
	@TestSetup
    private static void setupTestData(){
        Profile platformEndUserProfile = UserUtils.getPlatformEndUserProfile();
        PermissionSet umaApplicationAdminPermissionSet = UserUtils.getUmaApplicationAdminPermissionSet();

        User applicationAdmin = TestDataService.createUser(new User(
            Username = 'test.application.admin.ext@bayer.com',
            ProfileId = platformEndUserProfile.Id,
            FederationIdentifier = 'ZZBBB'
        ));
        insert applicationAdmin;

        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment(
            PermissionSetId = umaApplicationAdminPermissionSet.Id,
            AssigneeId = applicationAdmin.Id
        );
        insert permissionSetAssignment;

        System.runAs(applicationAdmin){
            Account company = TestDataService.getDefaultAccount();
            insert company;

            Job_Role__c jobRole = TestDataService.getDefaultJobRole();
            insert jobRole;

            MAPV_Department__c mapvDepartment = TestDataService.getDefaultMapvDepartment();
            insert mapvDepartment;

            MAPV_Group__c mapvGroup = TestDataService.getDefaultMapvGroup();
            insert mapvGroup;

            Role_Matrix__c roleMatrix = TestDataService.createRoleMatrix(new Role_Matrix__c(
                Job_Role__c = jobRole.Id,
                MAPV_Department__c = mapvDepartment.Id,
                MAPV_Group__c = mapvGroup.Id,
                Company__c = company.Id
            ));
            insert roleMatrix;
        
            MyLearning_Program__c myLearningProgram = TestDataService.getDefaultMyLearningProgram();
            insert myLearningProgram;
            insert new Role_Matrix_ML__c(
                Role_Matrix__c = roleMatrix.Id,
                MyLearning_Program__c = myLearningProgram.Id
            );

            Prima_Role__c primaRole = TestDataService.getDefaultPrimaRole();
            insert primaRole;
            insert new Role_Matrix_Prima_Role__c(
                Role_Matrix__c = roleMatrix.Id,
                Prima_Role__c = primaRole.Id
            );

            Prima_Security_Group__c primaSecurityGroup = TestDataService.getDefaultPrimaSecurityGroup();
            insert primaSecurityGroup;
            insert new Role_Matrix_Prima_SG__c(
                Role_Matrix__c = roleMatrix.Id,
                Prima_Security_Group__c = primaSecurityGroup.Id
            );
        
            Job_Role__c jobRole1 = new Job_Role__c(
                Name = 'Test Job Role1',
                Main_Role_Add_on__c = JobRoleUtils.ROLE_ADD_ON
            );
            insert jobRole1;
        
            Role_Matrix__c roleMatrix1 = TestDataService.createRoleMatrix(new Role_Matrix__c(
                Job_Role__c = jobRole1.Id,
                Role_Matrix_Type__c  ='Global Job role/ Add-On role',
                MAPV_Department__c = mapvDepartment.Id,
                MAPV_Group__c = mapvGroup.Id,
                Company__c = company.Id
            ));
            insert roleMatrix1;
        }
    }
    
    //function to test the Service class methods which returns RoleMatrixData along with 
    //MyLearnings, Prima Roles and Prima SG as a UMA admin
    @isTest
    private static void getRoleMatricesDataTest(){
        User applicationAdmin = [SELECT Id FROM User WHERE Username = 'test.application.admin.ext@bayer.com'];

        List<Role_Matrix__c> roleMatrix = [SELECT Id FROM Role_Matrix__c LIMIT 2];
        Set<String> roleMatrixIds = new Set<String>{roleMatrix[0].Id, roleMatrix[1].Id};

        List<RoleMatrixData> roleMatricesData;
        List<Role_Matrix__c> roleMatrices;
        Map<Id, MyLearning_Program__c> newMyLearningPrograms;
        Map<Id, Prima_Role__c> newPrimaRoles;
        Map<Id, Prima_Security_Group__c> newPrimaSecurityGroups;
        RoleMatrixData roleMatrix2;
        RoleMatrixData roleMatrix3;

        Test.startTest();
        
        System.runAs(applicationAdmin){
            roleMatricesData = RoleMatrixService.getRoleMatricesData(roleMatrixIds);
            roleMatrices = RoleMatrixUtils.getRoleMatrices(roleMatrixIds);
            newMyLearningPrograms = RoleMatrixService.getMyLearningProgramsMap(roleMatrices);
            newPrimaRoles = RoleMatrixService.getPrimaRolesMap(roleMatrices);
            newPrimaSecurityGroups = RoleMatrixService.getPrimaSecurityGroupsMap(roleMatrices);
            roleMatrix2 = RoleMatrixService.getRoleMatrixData('');
            roleMatrix3 = RoleMatrixService.getRoleMatrixData(roleMatrix[0].Id);
        }
        
        Test.stopTest();
        
        System.assertEquals(2, roleMatricesData.size());
        System.assertEquals(2, roleMatrices.size());
        System.assertEquals(1, newMyLearningPrograms.size());
        System.assertEquals(1, newPrimaRoles.size());
        System.assertEquals(1, newPrimaSecurityGroups.size());
        System.assertEquals(null, roleMatrix2);
        System.assertEquals(1, roleMatrix3.myLearningPrograms.size());
    }
}