force-app/main/default/objects/Integration_Config__mdt/Integration_Config__mdt.object-meta.xml
<CustomObject>
    <label>Integration Config</label>
    <pluralLabel>Integration Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Config__mdt/fields/Prima_Authtoken__c.field-meta.xml
<CustomField>
    <fullName>Prima_Authtoken__c</fullName>
    <label>Prima Authtoken</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UMA_Settings__mdt/UMA_Settings__mdt.object-meta.xml
<CustomObject>
    <label>UMA Settings</label>
    <pluralLabel>UMA Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UMA_Settings__mdt/fields/Max_nr_of_Prima_POST_request_attempts__c.field-meta.xml
<CustomField>
    <fullName>Max_nr_of_Prima_POST_request_attempts__c</fullName>
    <description>Specify maximum number of attempts for PRIMA POST request.</description>
    <inlineHelpText>Specify maximum number of attempts for PRIMA POST request.</inlineHelpText>
    <label>Max nr of Prima POST request attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Initial_Sending_Failed__c.field-meta.xml
<CustomField>
    <fullName>Initial_Sending_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when initial sending to Prima (triggered after changes are approved) results with error.</description>
    <label>Initial Sending Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Prima_Security_Group__c/User_Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>User Prima Security Group</label>
    <nameField>
        <displayFormat>UPG-{00000000}</displayFormat>
        <label>User Prima Security Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Security_Group__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Security Groups</relationshipLabel>
    <relationshipName>User_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PrimaService.cls
public with sharing class PrimaService {

    private static final Boolean IS_SANDBOX = OrgUtils.isSandbox();
    private static final String PRIMA_WEBHOOK_URL = '/connector/UMA/UMA_Endpoint/webhook.rsb';

    public class PrimaRequest {
        public List<PrimaData.UserRequest> users;
    }

    public class PrimaException extends Exception {}

    public static void sendPrimaUpdates(List<User_Entry__c> userEntries, Integer nrOfAttempts){
        PrimaRequest request = new PrimaRequest();
        request.users =  new List<PrimaData.UserRequest>();
        List<User_Prima_Role__c> userPrimaRoles = new List<User_Prima_Role__c>();
        List<User_Prima_Security_Group__c> userPrimaSecurityGroups = new List<User_Prima_Security_Group__c>();
        for(User_Entry__c userEntry : userEntries){ 
            PrimaData.UserRequest userRequest = new PrimaData.UserRequest(userEntry);       
            request.users.add(userRequest);
            if(!userEntry.User_Prima_Roles__r.isEmpty()){
                userPrimaRoles.addAll(userEntry.User_Prima_Roles__r);
            }
            if(!userEntry.User_Prima_Security_Groups__r.isEmpty()){
                userPrimaSecurityGroups.addAll(userEntry.User_Prima_Security_Groups__r);
            }
        }

        try {
            sendPrimaRolesAndSecurityGroups(request);
            updatePrimaRoleStatuses(userPrimaRoles);
            updatePrimaSecurityGroupStatuses(userPrimaSecurityGroups);
        } catch(Exception ex){
            UMA_Settings__mdt umaSettings = OrgUtils.getUmaSettings();
            if(umaSettings != null && nrOfAttempts < umaSettings.Max_nr_of_Prima_POST_request_attempts__c){
                System.enqueueJob(new PrimaUpdatesAsync(userEntries, nrOfAttempts + 1));
            } else {
                updatePrimaRoleSendingFailed(userPrimaRoles);
                updatePrimaSecurityGroupSendingFailed(userPrimaSecurityGroups);
                HandleCustomException.logException(ex);
            }
        }
    }

    private static void sendPrimaRolesAndSecurityGroups(PrimaRequest primaRequest){
        Integration_Config__mdt integrationConfig = OrgUtils.getIntegrationConfig();
        
        String endpoint = IS_SANDBOX ? 'callout:Prima_DEV' : 'callout:Prima';
        endpoint += PRIMA_WEBHOOK_URL;
        
        Map<String, String> header = new Map<String, String>{
            'Content-Type' => 'application/json',
            'x-arcesb-authtoken' => integrationConfig.Prima_Authtoken__c
        };

        String body = JSON.serialize(primaRequest);

        HttpResponse response = RESTCallout.makePostRequest(endpoint, header, body);
        System.debug('RESPONSE: '+response.getBody());
        if(response.getStatusCode() != 200){
            throw new PrimaException(response.getStatus());
        }
    }

    private static void updatePrimaRoleStatuses(List<User_Prima_Role__c> userPrimaRoles){
        for(User_Prima_Role__c userPrimaRole : userPrimaRoles){
            userPrimaRole.Status__c = getNewPrimaStatus(userPrimaRole.Status__c);
        }
        update userPrimaRoles;
    }

    private static void updatePrimaRoleSendingFailed(List<User_Prima_Role__c> userPrimaRoles){
        for(User_Prima_Role__c userPrimaRole : userPrimaRoles){
            userPrimaRole.Initial_Sending_Failed__c = true;
        }
        update userPrimaRoles;
    }
    
    private static void updatePrimaSecurityGroupStatuses(List<User_Prima_Security_Group__c> userPrimaSecurityGroups){
        for(User_Prima_Security_Group__c userPrimaSecurityGroup : userPrimaSecurityGroups){
            userPrimaSecurityGroup.Status__c = getNewPrimaStatus(userPrimaSecurityGroup.Status__c);
        }
        update userPrimaSecurityGroups;
    }

    private static void updatePrimaSecurityGroupSendingFailed(List<User_Prima_Security_Group__c> userPrimaSecurityGroups){
        for(User_Prima_Security_Group__c userPrimaSecurityGroup : userPrimaSecurityGroups){
            userPrimaSecurityGroup.Initial_Sending_Failed__c = true;
        }
        update userPrimaSecurityGroups;
    }

    private static String getNewPrimaStatus(String currentStatus){
        if(currentStatus == UserEntryData.STATUS_ASSIGN){
            return UserEntryData.STATUS_ASSIGN_REQUESTED;
        } else if(currentStatus == UserEntryData.STATUS_REMOVE){
            return UserEntryData.STATUS_REMOVE_REQUESTED;
        } else {
            return currentStatus;
        }
    }
}