force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <label>Job Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Job Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Main_Role_Add_on__c.field-meta.xml
<CustomField>
    <fullName>Main_Role_Add_on__c</fullName>
    <label>Main Role/Add-on</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Role</label>
    <referenceTo>Job_Role__c</referenceTo>
    <relationshipLabel>Role Matrices</relationshipLabel>
    <relationshipName>Role_Matrices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/CWID__c.field-meta.xml
<CustomField>
    <fullName>CWID__c</fullName>
    <label>CWID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Grant_access_to_UMA__c.field-meta.xml
<CustomField>
    <fullName>Grant_access_to_UMA__c</fullName>
    <inlineHelpText>Select &quot;Yes&quot; if you want to allow user to login to UMA application.</inlineHelpText>
    <label>Grant access to UMA</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <label>Locations</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czechia</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>Staff_Status__c</fullName>
    <label>Staff Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Long-Term Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Entry__c/fields/Time_Tracking_Required__c.field-meta.xml
<CustomField>
    <fullName>Time_Tracking_Required__c</fullName>
    <inlineHelpText>• REQUIRED - Position requires TT
• NOT REQUIRED - Position does not require TT​  
  • UPDATE EXISTING -  Existing TT account requires updates (Resource Manager, Cost Center)</inlineHelpText>
    <label>Time Tracking Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Update Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>Staff_Status__c</fullName>
    <formula>TEXT(User_Entry__r.Staff_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Staff Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/User_Time_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Time Tracking</label>
    <nameField>
        <displayFormat>UTTN-{0000}</displayFormat>
        <label>User Time Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Time Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Time_Tracking__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>Staff_Status__c</fullName>
    <formula>TEXT(User_Entry__r.Staff_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Staff Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/Time_Tracking_Required__c.field-meta.xml
<CustomField>
    <fullName>Time_Tracking_Required__c</fullName>
    <formula>TEXT(User_Entry__r.Time_Tracking_Required__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Tracking Required</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Time Trackings</relationshipLabel>
    <relationshipName>User_Time_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataService.cls
@isTest
public class TestDataService {

    public static User getDefaultUser(){
        return new User(
            Username = 'testuser@example.com.bayer',
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            Alias = 'test',
            TimeZoneSidKey = 'Europe/Berlin',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
    }

    public static User createUser(User prototype){
        User defaultUser = getDefaultUser();
        return (User) create(prototype, defaultUser);
    }

    public static Account getDefaultAccount(){
        return new Account(
            Name = 'Bayer'
        );
    }

    public static Account createAccount(Account prototype){
        Account defaultAccount = getDefaultAccount();
        return (Account) create(prototype, defaultAccount);
    }

    public static User_Entry__c getDefaultUserEntry(){
        return new User_Entry__c(
            First_Name__c = 'John',
            Last_Name__c = 'Test',
            Email__c = 'john.test@bayer.com',
            CWID__c = 'BYXXF',
            Staff_Status__c = UserEntryUtils.STAFF_STATUS_CURRENT,
            Locations__c = UserEntryUtils.LOCATION_GERMANY_BERLIN,
            Grant_access_to_UMA__c = UserEntryUtils.GRANT_ACCESS_TO_UMA_NO,
            Time_Tracking_Required__c = UserEntryUtils.TIME_TRACKING_NOT_REQUIRED
        );
    }

    public static User_Entry__c createUserEntry(User_Entry__c prototype){
        User_Entry__c defaultUserEntry = getDefaultUserEntry();
        return (User_Entry__c) create(prototype, defaultUserEntry);
    }

    public static Job_Role__c getDefaultJobRole(){
        return new Job_Role__c(
            Name = 'Test Job Role',
            Main_Role_Add_on__c = JobRoleUtils.ROLE_MAIN
        );
    }

    public static MAPV_Department__c getDefaultMapvDepartment(){
        return new MAPV_Department__c(
            Name = 'Test Department'
        );
    }

    public static MAPV_Group__c getDefaultMapvGroup(){
        return new MAPV_Group__c(
            Name = 'Test Group'
        );
    }

    public static MyLearning_Program__c getDefaultMyLearningProgram(){
        return new MyLearning_Program__c(
            Name = 'Test ML Program',
            ID__c = 'TEST_ML'
        );
    }

    public static MyLearning_Program__c createMyLearningProgram(MyLearning_Program__c prototype){
        MyLearning_Program__c defaultMyLearningProgram = getDefaultMyLearningProgram();
        return (MyLearning_Program__c) create(prototype, defaultMyLearningProgram);
    }

    public static Prima_Role__c getDefaultPrimaRole(){
        return new Prima_Role__c(
            Name = 'Test Prima Role'
        );
    }

    public static Prima_Security_Group__c getDefaultPrimaSecurityGroup(){
        return new Prima_Security_Group__c(
            Name = 'Test Prima Security Group'
        );
    }

    public static Role_Matrix__c getDefaultRoleMatrix(){
        return new Role_Matrix__c(
        	Role_Matrix_Type__c = '4-Criteria Role Matrix'
        );
    }

    public static Role_Matrix__c createRoleMatrix(Role_Matrix__c prototype){
        Role_Matrix__c defaultRoleMatrix = getDefaultRoleMatrix();
        return (Role_Matrix__c) create(prototype, defaultRoleMatrix);
    }
    
    public static User_Time_Tracking__c getDefaultUserTimeTracking(){
        return new User_Time_Tracking__c(
            Status__c = 'Assign',
            Name__c = 'User Time Tracking'
        );
    }
    
    public static User_Time_Tracking__c createUserTimeTracking(User_Time_Tracking__c prototype){
        User_Time_Tracking__c defaultUserTimeTracking = getDefaultUserTimeTracking();
        return (User_Time_Tracking__c) create(prototype, defaultUserTimeTracking);
    }
    
    public static User_MyLearning_Program__c getDefaultUserMyLearningProgram(){
        return new User_MyLearning_Program__c(
            Status__c = 'Assign'
        );
    }
    
    public static User_MyLearning_Program__c createUserMyLearningProgram(User_MyLearning_Program__c prototype){
        User_MyLearning_Program__c defaultUserMyLearningProgram = getDefaultUserMyLearningProgram();
        return (User_MyLearning_Program__c) create(prototype, defaultUserMyLearningProgram);
    }
    
    public static Role_Matrix_ML__c createRoleMatrixMyLearningProgram(Role_Matrix_ML__c rmmlp){
        return new Role_Matrix_ML__c(
            MyLearning_Program__c = rmmlp.MyLearning_Program__c,
            Role_Matrix__c = rmmlp.Role_Matrix__c
        );
    }

    private static SObject create(SObject prototype, SObject defaultObject){
        Map<String, Object> prototypeFields = prototype.getPopulatedFieldsAsMap();
        for(String fieldName : prototypeFields.keySet()){
            defaultObject.put(fieldName, prototypeFields.get(fieldName));
        }

        return defaultObject;
    }
}