force-app/main/default/objects/Account/fields/Tax_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_Number__c</fullName>
    <label>Tax ID Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <description>Main object of Donations application. Used to store the details about donation request.</description>
    <label>Donation</label>
    <nameField>
        <label>Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Donation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Focus_Area__c.field-meta.xml
<CustomField>
    <fullName>Focus_Area__c</fullName>
    <label>Focus Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Health for all - Child Health</fullName>
            </value>
            <value>
                <fullName>Health for all - Reproductive Health (Contraception)</fullName>
            </value>
            <value>
                <fullName>Health for all - Self care and access to health programs for vulnerable groups in LMIC</fullName>
            </value>
            <value>
                <fullName>Health for all - Public Health</fullName>
            </value>
            <value>
                <fullName>Climate Change</fullName>
            </value>
            <value>
                <fullName>Biodiversity</fullName>
            </value>
            <value>
                <fullName>Water Management</fullName>
            </value>
            <value>
                <fullName>Waste Management</fullName>
            </value>
            <value>
                <fullName>Hunger for none - Food security, food loss, food quality</fullName>
            </value>
            <value>
                <fullName>Hunger for none - Food availability (vulnerable groups)</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Support of frontier research in the life sciences, data science and environmental sciences</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Development of science talents</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Supporting education programs in the Life Sciences, environmental science and data science</fullName>
            </value>
            <value>
                <fullName>Science for a Better Life -  Science and Society</fullName>
            </value>
            <value>
                <fullName>Others (Exceptional)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <label>IBAN</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <label>Organization Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>HCO</fullName>
            </value>
            <value>
                <fullName>Med. Institute</fullName>
            </value>
            <value>
                <fullName>Health Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Origin_of_Funding__c.field-meta.xml
<CustomField>
    <fullName>Origin_of_Funding__c</fullName>
    <inlineHelpText>Applicant ensures that the donation is included in the donation budget</inlineHelpText>
    <label>Origin of Funding</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Divisional budget</fullName>
            </value>
            <value>
                <fullName>PS Site Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Overall_Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Overall_Net_Amount__c</fullName>
    <label>Overall Net Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Mr. and Mrs.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Wait for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation__c/fields/Tax_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_ID_Number__c</fullName>
    <label>Tax ID Number</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/Record_History__c.object-meta.xml
<CustomObject>
    <description>Custom history tracking of objects fields and related objects</description>
    <label>Record History</label>
    <nameField>
        <displayFormat>RH-{0000000}</displayFormat>
        <label>Record History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Field Updated</fullName>
            </value>
            <value>
                <fullName>Related Record Created</fullName>
            </value>
            <value>
                <fullName>Related Record Field Updated</fullName>
            </value>
            <value>
                <fullName>Related Record Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donation</label>
    <referenceTo>Donation__c</referenceTo>
    <relationshipLabel>Record History</relationshipLabel>
    <relationshipName>Record_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_History__c/fields/Original_Value__c.field-meta.xml
<CustomField>
    <fullName>Original_Value__c</fullName>
    <label>Original Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BV-PH-GUOP</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-GUOC</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-VU</fullName>
    </customValue>
    <customValue>
        <fullName>BV-PH-GUC</fullName>
    </customValue>
    <customValue>
        <fullName>JPH-WH</fullName>
    </customValue>
    <customValue>
        <fullName>BV-CH</fullName>
    </customValue>
    <customValue>
        <fullName>BV-CH-GERM</fullName>
    </customValue>
    <description>Business Unit is used in Donation and Approval Configuration</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonationTriggerHandlerTest.cls
@isTest
public class DonationTriggerHandlerTest {
    @TestSetup
    static void setupTestData() {
        
        Account acc= TestDataService.getDefaultAccount();
        
        User requestor = TestDataService.getDefaultUser();
        
        Donation__c oldDonation = new Donation__c(
            Status__c = 'Draft',
            Focus_Area__c = 'Waste Management',
            Salutation__c = 'Mr.',
            Account__c= acc.id,
            Account_Name__c= acc.Name,
            Requestor__c = requestor.id,
            Overall_Net_Amount__c=5100,
            Organization_Type__c='Agency',
            Contact_First_Name__c='test',
            Contact_Last_Name__c='ing',
            Contact_Email__c='test@gmail.com',
            Bank__c='icic',
            IBAN__c='DE12345678901234567890',
            Business_Unit__c='BV-PH-VU',
            Origin_of_Funding__c='Divisional budget',
            Tax_ID_Number__c='testttt'
            
        );
        insert oldDonation;
    }
    
    @isTest
    static void testMultipleFieldsUpdate(){
        Donation__c oldDonation = [SELECT Id, Name, Account__c, Contact_Email__c, Contact_First_Name__c, Contact_Last_Name__c, Status__c, Salutation__c, Requestor__c, Overall_Net_Amount__c, Organization_Type__c, Bank__c, IBAN__c, Business_Unit__c, Focus_Area__c FROM Donation__c LIMIT 1 ];
        Account accNew= TestDataService.getDefaultAccount();
        accNew.Name = 'Bayer - Donation';
        insert accNew;
        
        Profile platformEndUserProfile = UserUtils.getPlatformEndUserProfile();
        User requestor = TestDataService.createUser(new User(
            Username = 'test.requestor.ext@bayer.com',
            ProfileId = platformEndUserProfile.Id,
            FederationIdentifier = 'ADCBA'
        ));
        insert requestor;
        
        Donation__c newDonation = new Donation__c(
            id = oldDonation.id,
            Status__c = 'Approved',
            Focus_Area__c = 'Water Management',
            Salutation__c = 'Mrs.',
            Account_Name__c= accNew.Name,
            Requestor__c = requestor.id,
            Overall_Net_Amount__c= 50000,
            Organization_Type__c='HCO',
            Contact_First_Name__c='Test Donation',
            Contact_Last_Name__c='Contact',
            Contact_Email__c='TestContact@example.com',
            Bank__c='WBO',
            IBAN__c='DE12345678901234560987',
            Business_Unit__c='BV-PH-GU-Oph',
            Origin_of_Funding__c='PS Site Budget',
            Tax_ID_Number__c='testtax'
            
        );
        update newDonation;
        
        List<Record_History__c> recordHistoryList = [SELECT Action__c, Field__c, Original_Value__c, New_Value__c,Donation__c FROM Record_History__c where Donation__c=:newDonation.Id];
        System.assertEquals(15, recordHistoryList.size(), 'Expected 15 Record_History__c records to be created for 15 field updates.');
        
    }
    
    
}