force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserMyLearningProgramTriggerHandler.cls
public class UserMyLearningProgramTriggerHandler extends TriggerHandler {

    public override void beforeDelete(Map<Id, SObject> oldRecords){
        Map<Id, User_MyLearning_Program__c> oldUserMyLearningPrograms = (Map<Id, User_MyLearning_Program__c>) oldRecords;
        UserMyLearningProgramUtils.validateUserMyLearningProgramsOnDelete(oldUserMyLearningPrograms);
    }
    
    public override void afterDelete(Map<Id, SObject> oldRecords){
        Map<Id, User_MyLearning_Program__c> oldUserMyLearningPrograms = (Map<Id, User_MyLearning_Program__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(oldUserMyLearningPrograms.values());
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }
    
    public override void afterUpdate(Map<Id, SObject> newRecords, Map<Id, SObject> oldRecords) {
        Map<Id, User_MyLearning_Program__c> newUserMyLearningPrograms = (Map<Id, User_MyLearning_Program__c>) newRecords;
        Map<Id, User_MyLearning_Program__c> oldUserMyLearningPrograms = (Map<Id, User_MyLearning_Program__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(newUserMyLearningPrograms, oldUserMyLearningPrograms);
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }

    private static Set<Id> getUserEntryIds(List<User_MyLearning_Program__c> userMyLearningPrograms){
        Set<Id> userEntryIds = new Set<Id>();
        for(User_MyLearning_Program__c userMyLearningProgram : userMyLearningPrograms){
            userEntryIds.add(userMyLearningProgram.User_Entry__c);
        }
        return userEntryIds;
    }

    private static Set<Id> getUserEntryIds(Map<Id, User_MyLearning_Program__c> newUserMyLearningPrograms, Map<Id, User_MyLearning_Program__c> oldUserMyLearningPrograms){
        Set<Id> userEntryIds = new Set<Id>();
        User_MyLearning_Program__c newUserMyLearningProgram, oldUserMyLearningProgram;
        for(Id userMyLearningProgramId : newUserMyLearningPrograms.keySet()){
            newUserMyLearningProgram = newUserMyLearningPrograms.get(userMyLearningProgramId);
            oldUserMyLearningProgram = oldUserMyLearningPrograms.get(userMyLearningProgramId);
            if(newUserMyLearningProgram.Status__c != oldUserMyLearningProgram.Status__c){
                userEntryIds.add(newUserMyLearningProgram.User_Entry__c);
            }
        }
        return userEntryIds;
    }
}