force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/User_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>User Prima Role</label>
    <nameField>
        <displayFormat>UPR-{00000000}</displayFormat>
        <label>User Prima Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Prima_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assign Requested</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Remove Requested</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Prima_Role__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Prima Roles</relationshipLabel>
    <relationshipName>User_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserPrimaRoleTriggerHandler.cls
public class UserPrimaRoleTriggerHandler extends TriggerHandler {

    public override void beforeDelete(Map<Id, SObject> oldRecords){
        Map<Id, User_Prima_Role__c> oldUserPrimaRoles = (Map<Id, User_Prima_Role__c>) oldRecords;
        UserPrimaRoleUtils.validateUserPrimaRolesOnDelete(oldUserPrimaRoles);
    }
    
    public override void afterDelete(Map<Id, SObject> oldRecords){
        Map<Id, User_Prima_Role__c> oldUserPrimaRoles = (Map<Id, User_Prima_Role__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(oldUserPrimaRoles.values());
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }
    
    public override void afterUpdate(Map<Id, SObject> newRecords, Map<Id, SObject> oldRecords) {
        Map<Id, User_Prima_Role__c> newUserPrimaRoles = (Map<Id, User_Prima_Role__c>) newRecords;
        Map<Id, User_Prima_Role__c> oldUserPrimaRoles = (Map<Id, User_Prima_Role__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(newUserPrimaRoles, oldUserPrimaRoles);
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }

    private static Set<Id> getUserEntryIds(List<User_Prima_Role__c> userPrimaRoles){
        Set<Id> userEntryIds = new Set<Id>();
        for(User_Prima_Role__c userPrimaRole : userPrimaRoles){
            userEntryIds.add(userPrimaRole.User_Entry__c);
        }
        return userEntryIds;
    }

    private static Set<Id> getUserEntryIds(Map<Id, User_Prima_Role__c> newUserPrimaRoles, Map<Id, User_Prima_Role__c> oldUserPrimaRoles){
        Set<Id> userEntryIds = new Set<Id>();
        User_Prima_Role__c newUserPrimaRole, oldUserPrimaRole;
        for(Id userMyLearningProgramId : newUserPrimaRoles.keySet()){
            newUserPrimaRole = newUserPrimaRoles.get(userMyLearningProgramId);
            oldUserPrimaRole = oldUserPrimaRoles.get(userMyLearningProgramId);
            if(newUserPrimaRole.Status__c != oldUserPrimaRole.Status__c){
                userEntryIds.add(newUserPrimaRole.User_Entry__c);
            }
        }
        return userEntryIds;
    }
}