force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Time_Tracking__c/User_Time_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Time Tracking</label>
    <nameField>
        <displayFormat>UTTN-{0000}</displayFormat>
        <label>User Time Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Time Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Time_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Time_Tracking__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User Time Trackings</relationshipLabel>
    <relationshipName>User_Time_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserTimeTrackingTriggerHandler.cls
public class UserTimeTrackingTriggerHandler extends TriggerHandler{
    
	public override void afterDelete(Map<Id, SObject> oldRecords){
        Map<Id, User_Time_Tracking__c> oldUserTimeTrackings = (Map<Id, User_Time_Tracking__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(oldUserTimeTrackings.values());
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }
    
    public override void afterUpdate(Map<Id, SObject> newRecords, Map<Id, SObject> oldRecords) {
        Map<Id, User_Time_Tracking__c> newUserTimeTrackings = (Map<Id, User_Time_Tracking__c>) newRecords;
        Map<Id, User_Time_Tracking__c> oldUserTimeTrackings = (Map<Id, User_Time_Tracking__c>) oldRecords;
        Set<Id> userEntryIds = getUserEntryIds(newUserTimeTrackings, oldUserTimeTrackings);
        UserEntryService.updateLockedUserEntries(userEntryIds);
    }
    
    private static Set<Id> getUserEntryIds(List<User_Time_Tracking__c> userTimeTrackings){
        Set<Id> userEntryIds = new Set<Id>();
        for(User_Time_Tracking__c userTimeTracking : userTimeTrackings){
            userEntryIds.add(userTimeTracking.User_Entry__c);
        }
        return userEntryIds;
    }
    
    private static Set<Id> getUserEntryIds(Map<Id, User_Time_Tracking__c> newUserTimeTrackings, Map<Id, User_Time_Tracking__c> oldUserTimeTrackings){
        Set<Id> userEntryIds = new Set<Id>();
        User_Time_Tracking__c newUserTimeTracking, oldUserTimeTracking;
        for(Id userTimeTrackingId : newUserTimeTrackings.keySet()){
            newUserTimeTracking = newUserTimeTrackings.get(userTimeTrackingId);
            oldUserTimeTracking = oldUserTimeTrackings.get(userTimeTrackingId);
            if(newUserTimeTracking.Status__c != oldUserTimeTracking.Status__c){
                userEntryIds.add(newUserTimeTracking.User_Entry__c);
            }
        }
        return userEntryIds;
    }
}