force-app/main/default/objects/Custom_Exception__c/Custom_Exception__c.object-meta.xml
<CustomObject>
    <description>Used to store exceptions from external systems, e.g. PRIMA</description>
    <label>Custom Exception</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Custom Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Exception__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Governor_Limits__c.field-meta.xml
<CustomField>
    <fullName>Governor_Limits__c</fullName>
    <label>Governor Limits</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HandleCustomException.cls
public without sharing class HandleCustomException extends Exception {
    public static void logException(Exception e)
    {
        logException(e, null);
    }

    public static void logException(Exception e, String relatedToId)
    {
        String stackTrace = e.getStackTraceString().substringBefore('\n');
        String className = stackTrace.substringAfter('.').substringBefore('.');
        String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');

        // Get current governor limits
        String queries = '1. Number of SOQL queries issued / Total number allowed: ' + Limits.getQueries() + '/' + Limits.getLimitQueries();
        String dmlRows = '2. Number of records processed with DML statements / Total number allowed: ' + Limits.getDmlRows() + '/' + Limits.getLimitDmlRows();
        String dmlStatements = '3. Number of DML statements called / Total number allowed: ' +  Limits.getDmlStatements() + '/' + Limits.getLimitDmlStatements();
        String cpuTime = '4. CPU time (in milliseconds) used / Maximum CPU time allowed: ' + Limits.getCpuTime() + '/' + Limits.getLimitCpuTime();

        // Log information as a custom object record after making sure permissions are fine
        if (Schema.sObjectType.Custom_Exception__c.isCreateable()) {
            insert new Custom_Exception__c(
                Related_To_Id__c = relatedToId,
                Exception_Message__c = e.getMessage(),
                Exception_Type__c = e.getTypeName(),
                Line_Number__c = e.getLineNumber(),
                Stack_Trace__c = stackTrace,
                Class_Name__c = className,
                Method_Name__c = methodName,
                Governor_Limits__c = String.format('{0}\n{1}\n{2}\n{3}', new List<String>{ queries, dmlRows, dmlStatements, cpuTime })
            );
        }
    }
    
    //Return error details string
    public static String debugException(Exception e)
    {
        String errorMessage;
        String stackTrace = e.getStackTraceString().substringBefore('\n');
        String className = stackTrace.substringAfter('.').substringBefore('.');
        String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');
        
        errorMessage += 'Method name: ' + methodName + '\n';
        errorMessage += 'Class name: ' + className + '\r\n';
        errorMessage += 'Exception type caught: ' + e.getTypeName() + '\r\n';
        errorMessage += 'Message: ' + e.getMessage() + '\r\n';
        errorMessage += 'Cause: ' + e.getCause() + '\r\n';
        errorMessage += 'Line number: ' + e.getLineNumber() + '\r\n';
        errorMessage += 'Stack trace: ' + e.getStackTraceString()+ '\r\n';
        return errorMessage;
    }
    
    
}