force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyLearning_Program__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_Entry__c/User_Entry__c.object-meta.xml
<CustomObject>
    <label>User Entry</label>
    <nameField>
        <label>User Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Entry__c/fields/CWID__c.field-meta.xml
<CustomField>
    <fullName>CWID__c</fullName>
    <label>CWID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/User_MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>User MyLearning Program</label>
    <nameField>
        <displayFormat>UML-{00000000}</displayFormat>
        <label>User MyLearning Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_MyLearning_Program__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assign</fullName>
                <label>To be Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
                <label>To be Removed</label>
            </value>
            <value>
                <fullName>Error</fullName>
                <isActive>false</isActive>
                <label>Error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_MyLearning_Program__c/fields/User_Entry__c.field-meta.xml
<CustomField>
    <fullName>User_Entry__c</fullName>
    <label>User Entry</label>
    <referenceTo>User_Entry__c</referenceTo>
    <relationshipLabel>User MyLearning Programs</relationshipLabel>
    <relationshipName>User_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MyLearningCurriculumsBatch.cls
public class MyLearningCurriculumsBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public final Set<Id> userEntryIds;
    
    public MyLearningCurriculumsBatch(Set<Id> ids){
        userEntryIds = ids;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT User_Entry__r.CWID__c, MyLearning_Program__r.ID__c, Status__c';
        query += ' FROM User_MyLearning_Program__c';
        query += ' WHERE User_Entry__c IN :userEntryIds AND Status__c = \'' + UserEntryData.STATUS_ASSIGN + '\'';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<User_MyLearning_Program__c> scope){
        List<User_MyLearning_Program__c> userMLProgramsToAssign = new List<User_MyLearning_Program__c>();
        List<User_MyLearning_Program__c> userMLProgramsToUpdate = new List<User_MyLearning_Program__c>();
        
        String curriculumStatus;
        for(User_MyLearning_Program__c userMLProgram : scope){
            curriculumStatus = MyLearningService.getCurriculumStatus(
                userMLProgram.User_Entry__r.CWID__c, 
                userMLProgram.MyLearning_Program__r.ID__c
            );
            if(MyLearningService.isCurriculumAssigned(curriculumStatus)){
                userMLProgram.Status__c = UserEntryData.STATUS_ASSIGNED;
                userMLProgramsToUpdate.add(userMLProgram);
            } else {
                userMLProgramsToAssign.add(userMLProgram);
            }
        }
        
        if(!userMLProgramsToAssign.isEmpty()){
            Map<String, Map<String, MyLearningService.CurriculumResponse>> curriculumResponseMap = MyLearningService.assignCurriculums(userMLProgramsToAssign);
            
            MyLearningService.CurriculumResponse response;
            for(User_MyLearning_Program__c userMLProgram : userMLProgramsToAssign){
                response = MyLearningService.getCurriculumResponse(
                    curriculumResponseMap, 
                    userMLProgram.User_Entry__r.CWID__c, 
                    userMLProgram.MyLearning_Program__r.ID__c
                );
                if(response != null && response.errorMessage == null){
                    userMLProgram.Status__c = UserEntryData.STATUS_ASSIGNED;
                    userMLProgramsToUpdate.add(userMLProgram);
                } else if(response != null){
                    userMLProgram.Status__c = UserEntryData.STATUS_ERROR;
                    userMLProgram.Error_Message__c = response.errorMessage;
                    userMLProgramsToUpdate.add(userMLProgram);
                }
            }
        }
        
        update userMLProgramsToUpdate;
    }

    public void finish(Database.BatchableContext BC){}
}