force-app/main/default/objects/MyLearning_Program__c/MyLearning_Program__c.object-meta.xml
<CustomObject>
    <label>MyLearning Program</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage MyLearning Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Role__c/Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Prima Role</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prima_Security_Group__c/Prima_Security_Group__c.object-meta.xml
<CustomObject>
    <label>Prima Security Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manage Prima Security Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix__c/Role_Matrix__c.object-meta.xml
<CustomObject>
    <label>Role Matrix</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Role Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/Role_Matrix_ML__c.object-meta.xml
<CustomObject>
    <label>Role Matrix MyLearning Program</label>
    <nameField>
        <displayFormat>Role Matrix ML-{0000}</displayFormat>
        <label>Role Matrix ML</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix MyLearning Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_ML__c/fields/MyLearning_Program__c.field-meta.xml
<CustomField>
    <fullName>MyLearning_Program__c</fullName>
    <label>MyLearning Program</label>
    <referenceTo>MyLearning_Program__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_ML__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix MyLearning Programs</relationshipLabel>
    <relationshipName>Role_Matrix_MyLearning_Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/Role_Matrix_Prima_Role__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Role</label>
    <nameField>
        <displayFormat>Role Matrix PR-{0000}</displayFormat>
        <label>Role Matrix Prima Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Prima_Role__c.field-meta.xml
<CustomField>
    <fullName>Prima_Role__c</fullName>
    <label>Prima Role</label>
    <referenceTo>Prima_Role__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_Role__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Roles</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/Role_Matrix_Prima_SG__c.object-meta.xml
<CustomObject>
    <label>Role Matrix Prima Security Group</label>
    <nameField>
        <displayFormat>Role Matrix PrimaSG-{0000}</displayFormat>
        <label>Role Matrix Prima Security Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Matrix Prima Security Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Prima_Security_Group__c.field-meta.xml
<CustomField>
    <fullName>Prima_Security_Group__c</fullName>
    <label>Prima Security Group</label>
    <referenceTo>Prima_Security_Group__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role_Matrix_Prima_SG__c/fields/Role_Matrix__c.field-meta.xml
<CustomField>
    <fullName>Role_Matrix__c</fullName>
    <label>Role Matrix</label>
    <referenceTo>Role_Matrix__c</referenceTo>
    <relationshipLabel>Role Matrix Prima Security Groups</relationshipLabel>
    <relationshipName>Role_Matrix_Prima_Security_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoleMatrixService.cls
public class RoleMatrixService {

    public static RoleMatrixData getRoleMatrixData(String roleMatrixId){
        if(String.isBlank(roleMatrixId)){
            return null;
        }

        Role_Matrix__c roleMatrix = RoleMatrixUtils.getRoleMatrix(roleMatrixId);
        RoleMatrixData roleMatrixData = roleMatrix != null ? new RoleMatrixData(roleMatrix) : new RoleMatrixData();

        return roleMatrixData;
    }
    
    public static List<RoleMatrixData> getRoleMatricesData(Set<String> roleMatrixIds){
        List<RoleMatrixData> roleMatricesData = new List<RoleMatrixData>();
        if(roleMatrixIds == null){
            return roleMatricesData;
        }

        List<Role_Matrix__c> roleMatrices = RoleMatrixUtils.getRoleMatrices(roleMatrixIds);
        for(Role_Matrix__c roleMatrix : roleMatrices){
            RoleMatrixData roleMatrixData = roleMatrix != null ? new RoleMatrixData(roleMatrix) : new RoleMatrixData();
            roleMatricesData.add(roleMatrixData);
        }

        return roleMatricesData;
    }

    public static Map<Id, MyLearning_Program__c> getMyLearningProgramsMap(List<Role_Matrix__c> roleMatrices){
        Map<Id, MyLearning_Program__c> newMyLearningPrograms = new Map<Id, MyLearning_Program__c>();
        for(Role_Matrix__c roleMatrix : roleMatrices){
            for(Role_Matrix_ML__c roleMatrixMyLearningProgram : roleMatrix.Role_Matrix_MyLearning_Programs__r){
                if(!newMyLearningPrograms.containsKey(roleMatrixMyLearningProgram.MyLearning_Program__c)){
                    newMyLearningPrograms.put(
                        roleMatrixMyLearningProgram.MyLearning_Program__c, 
                        new MyLearning_Program__c(
                            Id = roleMatrixMyLearningProgram.MyLearning_Program__c,
                            Name = roleMatrixMyLearningProgram.MyLearning_Program__r.Name
                        )
                    );
                }
            }
        }
        return newMyLearningPrograms;
    }

    public static Map<Id, Prima_Role__c> getPrimaRolesMap(List<Role_Matrix__c> roleMatrices){
        Map<Id, Prima_Role__c> newPrimaRoles = new Map<Id, Prima_Role__c>();
        for(Role_Matrix__c roleMatrix : roleMatrices){
            for(Role_Matrix_Prima_Role__c roleMatrixPrimaRole : roleMatrix.Role_Matrix_Prima_Roles__r){
                if(!newPrimaRoles.containsKey(roleMatrixPrimaRole.Prima_Role__c)){
                    newPrimaRoles.put(
                        roleMatrixPrimaRole.Prima_Role__c, 
                        new Prima_Role__c(
                            Id = roleMatrixPrimaRole.Prima_Role__c,
                            Name = roleMatrixPrimaRole.Prima_Role__r.Name
                        )
                    );
                }
            }
        }
        return newPrimaRoles;
    }

    public static Map<Id, Prima_Security_Group__c> getPrimaSecurityGroupsMap(List<Role_Matrix__c> roleMatrices){
        Map<Id, Prima_Security_Group__c> newPrimaSecurityGroups = new Map<Id, Prima_Security_Group__c>();
        for(Role_Matrix__c roleMatrix : roleMatrices){
            for(Role_Matrix_Prima_SG__c roleMatrixPrimaSecurityGroup : roleMatrix.Role_Matrix_Prima_Security_Groups__r){
                if(!newPrimaSecurityGroups.containsKey(roleMatrixPrimaSecurityGroup.Prima_Security_Group__c)){
                    newPrimaSecurityGroups.put(
                        roleMatrixPrimaSecurityGroup.Prima_Security_Group__c, 
                        new Prima_Security_Group__c(
                            Id = roleMatrixPrimaSecurityGroup.Prima_Security_Group__c,
                            Name = roleMatrixPrimaSecurityGroup.Prima_Security_Group__r.Name
                        )
                    );
                }
            }
        }
        return newPrimaSecurityGroups;
    }
}